// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Tracing implementation internals

#include "verilated_vcd_c.h"
#include "Vtop__Syms.h"


VL_ATTR_COLD void Vtop___024root__trace_init_sub__TOP__constants_pkg__0(Vtop___024root* vlSelf, VerilatedVcd* tracep);

VL_ATTR_COLD void Vtop___024root__trace_init_sub__TOP__0(Vtop___024root* vlSelf, VerilatedVcd* tracep) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_init_sub__TOP__0\n"); );
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Body
    const int c = vlSymsp->__Vm_baseCode;
    tracep->pushPrefix("$rootio", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+1,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+2,0,"rst",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+3,0,"trap",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+4,0,"led",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->popPrefix();
    tracep->pushPrefix("constants_pkg", VerilatedTracePrefixType::SCOPE_MODULE);
    Vtop___024root__trace_init_sub__TOP__constants_pkg__0(vlSelf, tracep);
    tracep->popPrefix();
    tracep->pushPrefix("top_soc", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+5,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+6,0,"rst",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+7,0,"trap",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+8,0,"led",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBit(c+9,0,"pcpi_valid",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+10,0,"pcpi_insn",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+11,0,"pcpi_rs1",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+12,0,"pcpi_rs2",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+13,0,"pcpi_wr",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+14,0,"pcpi_rd",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+15,0,"pcpi_wait",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+16,0,"pcpi_ready",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+17,0,"mem_valid",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+18,0,"mem_instr",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+19,0,"mem_ready",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+20,0,"mem_addr",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+21,0,"mem_wdata",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+22,0,"mem_wstrb",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+23,0,"mem_rdata",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+24,0,"bram_addr",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 13,0);
    tracep->declBit(c+25,0,"mem_ready_reg",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+26,0,"led_reg",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBit(c+27,0,"select_led",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+28,0,"select_inp_bram",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+29,0,"select_wt_bram",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+30,0,"select_bram",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+31,0,"select_bnn_axi",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+32,0,"inp_bram_addr",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+33,0,"inp_bram_dout",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+34,0,"wt_bram_addr",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+35,0,"wt_bram_dout",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+36,0,"axi_awready",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+37,0,"axi_wready",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+38,0,"axi_bvalid",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+39,0,"axi_arready",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+40,0,"axi_rvalid",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+41,0,"axi_rdata",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->pushPrefix("u_bnn_accelerator", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+42,0,"aclk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+43,0,"aresetn",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+44,0,"s_axi_awaddr",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+45,0,"s_axi_awvalid",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+46,0,"s_axi_awready",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+47,0,"s_axi_wdata",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+48,0,"s_axi_wvalid",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+49,0,"s_axi_wready",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+50,0,"s_axi_bvalid",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+51,0,"s_axi_bready",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+52,0,"s_axi_araddr",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+53,0,"s_axi_arvalid",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+54,0,"s_axi_arready",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+55,0,"s_axi_rdata",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+56,0,"s_axi_rvalid",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+57,0,"s_axi_rready",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+58,0,"s_axi_bresp",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+59,0,"s_axi_rresp",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+60,0,"inp_bram_addr",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+61,0,"inp_bram_dout",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+62,0,"wt_bram_addr",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+63,0,"wt_bram_dout",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+64,0,"ctrl_reg",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+65,0,"in_ptr_reg",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+66,0,"wt_ptr_reg",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+67,0,"bnn_start",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+68,0,"bnn_busy",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+69,0,"bnn_done",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+70,0,"bnn_result",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+71,0,"aw_ready",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+72,0,"w_ready",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+73,0,"b_valid",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+74,0,"ar_ready",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+75,0,"r_valid",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+76,0,"status_reg",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+77,0,"addr_read",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+78,0,"addr_write",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->pushPrefix("i_bnn_core", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+79,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+80,0,"rstn",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+81,0,"start",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+82,0,"in_ptr",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+83,0,"wt_ptr",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+84,0,"inp_bram_addr",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+85,0,"inp_bram_dout",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+86,0,"wt_bram_addr",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+87,0,"wt_bram_dout",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+88,0,"busy",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+89,0,"done",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+90,0,"result",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+91,0,"enable",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+92,0,"clear_accumulator",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+93,0,"pe_result",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 8,0);
    tracep->declBus(c+94,0,"state",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBus(c+95,0,"word_idx",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBus(c+96,0,"offset_count",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+97,0,"inputs_reg",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+98,0,"weights_reg",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->pushPrefix("pe", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+99,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+100,0,"rstn",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+101,0,"input_register",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+102,0,"weight_register",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+103,0,"neuron_value",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 8,0);
    tracep->declBit(c+104,0,"enable",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+105,0,"clear_accumulator",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+106,0,"xnor_result",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->pushPrefix("stage1", VerilatedTracePrefixType::ARRAY_UNPACKED);
    for (int i = 0; i < 16; ++i) {
        tracep->declBus(c+107+i*1,0,"",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, true,(i+0), 1,0);
    }
    tracep->popPrefix();
    tracep->pushPrefix("stage2", VerilatedTracePrefixType::ARRAY_UNPACKED);
    for (int i = 0; i < 8; ++i) {
        tracep->declBus(c+123+i*1,0,"",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, true,(i+0), 2,0);
    }
    tracep->popPrefix();
    tracep->pushPrefix("stage3", VerilatedTracePrefixType::ARRAY_UNPACKED);
    for (int i = 0; i < 4; ++i) {
        tracep->declBus(c+131+i*1,0,"",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, true,(i+0), 3,0);
    }
    tracep->popPrefix();
    tracep->pushPrefix("stage4", VerilatedTracePrefixType::ARRAY_UNPACKED);
    for (int i = 0; i < 2; ++i) {
        tracep->declBus(c+135+i*1,0,"",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, true,(i+0), 4,0);
    }
    tracep->popPrefix();
    tracep->declBus(c+137,0,"i",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::INTEGER, false,-1, 31,0);
    tracep->declBus(c+138,0,"sum_reg",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 5,0);
    tracep->declBus(c+139,0,"inp",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+140,0,"wt",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+141,0,"accumulator",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 8,0);
    tracep->popPrefix();
    tracep->popPrefix();
    tracep->popPrefix();
    tracep->pushPrefix("uut", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+408,0,"ENABLE_COUNTERS",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 0,0);
    tracep->declBus(c+408,0,"ENABLE_COUNTERS64",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 0,0);
    tracep->declBus(c+408,0,"ENABLE_REGS_16_31",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 0,0);
    tracep->declBus(c+408,0,"ENABLE_REGS_DUALPORT",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 0,0);
    tracep->declBus(c+409,0,"LATCHED_MEM_RDATA",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 0,0);
    tracep->declBus(c+408,0,"TWO_STAGE_SHIFT",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 0,0);
    tracep->declBus(c+409,0,"BARREL_SHIFTER",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 0,0);
    tracep->declBus(c+409,0,"TWO_CYCLE_COMPARE",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 0,0);
    tracep->declBus(c+409,0,"TWO_CYCLE_ALU",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 0,0);
    tracep->declBus(c+409,0,"COMPRESSED_ISA",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 0,0);
    tracep->declBus(c+408,0,"CATCH_MISALIGN",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 0,0);
    tracep->declBus(c+408,0,"CATCH_ILLINSN",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 0,0);
    tracep->declBus(c+408,0,"ENABLE_PCPI",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 0,0);
    tracep->declBus(c+409,0,"ENABLE_MUL",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 0,0);
    tracep->declBus(c+409,0,"ENABLE_FAST_MUL",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 0,0);
    tracep->declBus(c+409,0,"ENABLE_DIV",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 0,0);
    tracep->declBus(c+409,0,"ENABLE_IRQ",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 0,0);
    tracep->declBus(c+408,0,"ENABLE_IRQ_QREGS",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 0,0);
    tracep->declBus(c+408,0,"ENABLE_IRQ_TIMER",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 0,0);
    tracep->declBus(c+409,0,"ENABLE_TRACE",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 0,0);
    tracep->declBus(c+409,0,"REGS_INIT_ZERO",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 0,0);
    tracep->declBus(c+410,0,"MASKED_IRQ",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+411,0,"LATCHED_IRQ",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+410,0,"PROGADDR_RESET",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+412,0,"PROGADDR_IRQ",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+411,0,"STACKADDR",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+142,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+143,0,"resetn",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+144,0,"trap",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+145,0,"mem_valid",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+146,0,"mem_instr",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+147,0,"mem_ready",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+148,0,"mem_addr",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+149,0,"mem_wdata",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+150,0,"mem_wstrb",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+151,0,"mem_rdata",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+152,0,"mem_la_read",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+153,0,"mem_la_write",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+154,0,"mem_la_addr",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+155,0,"mem_la_wdata",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+156,0,"mem_la_wstrb",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBit(c+157,0,"pcpi_valid",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+158,0,"pcpi_insn",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+159,0,"pcpi_rs1",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+160,0,"pcpi_rs2",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+161,0,"pcpi_wr",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+162,0,"pcpi_rd",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+163,0,"pcpi_wait",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+164,0,"pcpi_ready",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+165,0,"irq",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+166,0,"eoi",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+167,0,"trace_valid",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declQuad(c+168,0,"trace_data",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 35,0);
    tracep->declBus(c+413,0,"irq_timer",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::INTEGER, false,-1, 31,0);
    tracep->declBus(c+414,0,"irq_ebreak",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::INTEGER, false,-1, 31,0);
    tracep->declBus(c+415,0,"irq_buserror",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::INTEGER, false,-1, 31,0);
    tracep->declBus(c+416,0,"irqregs_offset",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::INTEGER, false,-1, 31,0);
    tracep->declBus(c+416,0,"regfile_size",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::INTEGER, false,-1, 31,0);
    tracep->declBus(c+417,0,"regindex_bits",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::INTEGER, false,-1, 31,0);
    tracep->declBus(c+408,0,"WITH_PCPI",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 0,0);
    tracep->declQuad(c+418,0,"TRACE_BRANCH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 35,0);
    tracep->declQuad(c+420,0,"TRACE_ADDR",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 35,0);
    tracep->declQuad(c+422,0,"TRACE_IRQ",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 35,0);
    tracep->declQuad(c+170,0,"count_cycle",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 63,0);
    tracep->declQuad(c+172,0,"count_instr",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 63,0);
    tracep->declBus(c+174,0,"reg_pc",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+175,0,"reg_next_pc",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+176,0,"reg_op1",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+177,0,"reg_op2",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+178,0,"reg_out",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+179,0,"reg_sh",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+180,0,"next_insn_opcode",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+181,0,"dbg_insn_opcode",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+182,0,"dbg_insn_addr",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+183,0,"dbg_mem_valid",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+184,0,"dbg_mem_instr",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+185,0,"dbg_mem_ready",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+186,0,"dbg_mem_addr",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+187,0,"dbg_mem_wdata",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+188,0,"dbg_mem_wstrb",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+189,0,"dbg_mem_rdata",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+190,0,"next_pc",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+191,0,"irq_delay",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+192,0,"irq_active",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+193,0,"irq_mask",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+194,0,"irq_pending",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+195,0,"timer",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->pushPrefix("cpuregs", VerilatedTracePrefixType::ARRAY_UNPACKED);
    for (int i = 0; i < 32; ++i) {
        tracep->declBus(c+196+i*1,0,"",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, true,(i+0), 31,0);
    }
    tracep->popPrefix();
    tracep->declBus(c+228,0,"i",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::INTEGER, false,-1, 31,0);
    tracep->declBit(c+229,0,"pcpi_mul_wr",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+230,0,"pcpi_mul_rd",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+231,0,"pcpi_mul_wait",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+232,0,"pcpi_mul_ready",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+233,0,"pcpi_div_wr",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+234,0,"pcpi_div_rd",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+235,0,"pcpi_div_wait",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+236,0,"pcpi_div_ready",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+237,0,"pcpi_int_wr",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+238,0,"pcpi_int_rd",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+239,0,"pcpi_int_wait",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+240,0,"pcpi_int_ready",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+241,0,"mem_state",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+242,0,"mem_wordsize",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+243,0,"mem_rdata_word",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+244,0,"mem_rdata_q",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+245,0,"mem_do_prefetch",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+246,0,"mem_do_rinst",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+247,0,"mem_do_rdata",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+248,0,"mem_do_wdata",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+249,0,"mem_xfer",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+250,0,"mem_la_secondword",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+251,0,"mem_la_firstword_reg",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+252,0,"last_mem_valid",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+253,0,"mem_la_firstword",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+254,0,"mem_la_firstword_xfer",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+255,0,"prefetched_high_word",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+256,0,"clear_prefetched_high_word",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+257,0,"mem_16bit_buffer",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+258,0,"mem_rdata_latched_noshuffle",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+259,0,"mem_rdata_latched",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+260,0,"mem_la_use_prefetched_high_word",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+261,0,"mem_busy",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+262,0,"mem_done",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+263,0,"instr_lui",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+264,0,"instr_auipc",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+265,0,"instr_jal",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+266,0,"instr_jalr",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+267,0,"instr_beq",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+268,0,"instr_bne",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+269,0,"instr_blt",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+270,0,"instr_bge",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+271,0,"instr_bltu",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+272,0,"instr_bgeu",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+273,0,"instr_lb",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+274,0,"instr_lh",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+275,0,"instr_lw",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+276,0,"instr_lbu",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+277,0,"instr_lhu",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+278,0,"instr_sb",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+279,0,"instr_sh",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+280,0,"instr_sw",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+281,0,"instr_addi",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+282,0,"instr_slti",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+283,0,"instr_sltiu",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+284,0,"instr_xori",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+285,0,"instr_ori",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+286,0,"instr_andi",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+287,0,"instr_slli",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+288,0,"instr_srli",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+289,0,"instr_srai",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+290,0,"instr_add",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+291,0,"instr_sub",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+292,0,"instr_sll",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+293,0,"instr_slt",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+294,0,"instr_sltu",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+295,0,"instr_xor",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+296,0,"instr_srl",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+297,0,"instr_sra",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+298,0,"instr_or",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+299,0,"instr_and",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+300,0,"instr_rdcycle",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+301,0,"instr_rdcycleh",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+302,0,"instr_rdinstr",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+303,0,"instr_rdinstrh",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+304,0,"instr_ecall_ebreak",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+305,0,"instr_fence",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+306,0,"instr_getq",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+307,0,"instr_setq",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+308,0,"instr_retirq",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+309,0,"instr_maskirq",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+310,0,"instr_waitirq",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+311,0,"instr_timer",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+312,0,"instr_trap",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+313,0,"decoded_rd",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+314,0,"decoded_rs1",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+315,0,"decoded_rs2",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+316,0,"decoded_imm",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+317,0,"decoded_imm_j",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+318,0,"decoder_trigger",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+319,0,"decoder_trigger_q",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+320,0,"decoder_pseudo_trigger",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+321,0,"decoder_pseudo_trigger_q",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+322,0,"compressed_instr",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+323,0,"is_lui_auipc_jal",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+324,0,"is_lb_lh_lw_lbu_lhu",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+325,0,"is_slli_srli_srai",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+326,0,"is_jalr_addi_slti_sltiu_xori_ori_andi",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+327,0,"is_sb_sh_sw",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+328,0,"is_sll_srl_sra",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+329,0,"is_lui_auipc_jal_jalr_addi_add_sub",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+330,0,"is_slti_blt_slt",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+331,0,"is_sltiu_bltu_sltu",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+332,0,"is_beq_bne_blt_bge_bltu_bgeu",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+333,0,"is_lbu_lhu_lw",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+334,0,"is_alu_reg_imm",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+335,0,"is_alu_reg_reg",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+336,0,"is_compare",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+337,0,"is_rdcycle_rdcycleh_rdinstr_rdinstrh",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declQuad(c+338,0,"new_ascii_instr",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 63,0);
    tracep->declQuad(c+340,0,"dbg_ascii_instr",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 63,0);
    tracep->declBus(c+342,0,"dbg_insn_imm",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+343,0,"dbg_insn_rs1",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+344,0,"dbg_insn_rs2",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+345,0,"dbg_insn_rd",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+346,0,"dbg_rs1val",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+347,0,"dbg_rs2val",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+348,0,"dbg_rs1val_valid",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+349,0,"dbg_rs2val_valid",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declQuad(c+350,0,"q_ascii_instr",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 63,0);
    tracep->declBus(c+352,0,"q_insn_imm",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+353,0,"q_insn_opcode",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+354,0,"q_insn_rs1",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+355,0,"q_insn_rs2",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+356,0,"q_insn_rd",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBit(c+357,0,"dbg_next",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+358,0,"launch_next_insn",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+359,0,"dbg_valid_insn",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declQuad(c+360,0,"cached_ascii_instr",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 63,0);
    tracep->declBus(c+362,0,"cached_insn_imm",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+363,0,"cached_insn_opcode",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+364,0,"cached_insn_rs1",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+365,0,"cached_insn_rs2",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+366,0,"cached_insn_rd",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+424,0,"cpu_state_trap",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+425,0,"cpu_state_fetch",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+426,0,"cpu_state_ld_rs1",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+427,0,"cpu_state_ld_rs2",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+428,0,"cpu_state_exec",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+429,0,"cpu_state_shift",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+430,0,"cpu_state_stmem",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+431,0,"cpu_state_ldmem",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+367,0,"cpu_state",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+368,0,"irq_state",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declArray(c+369,0,"dbg_ascii_state",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declBit(c+373,0,"set_mem_do_rinst",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+374,0,"set_mem_do_rdata",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+375,0,"set_mem_do_wdata",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+376,0,"latched_store",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+377,0,"latched_stalu",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+378,0,"latched_branch",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+379,0,"latched_compr",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+380,0,"latched_trace",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+381,0,"latched_is_lu",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+382,0,"latched_is_lh",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+383,0,"latched_is_lb",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+384,0,"latched_rd",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+385,0,"current_pc",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+386,0,"pcpi_timeout_counter",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBit(c+387,0,"pcpi_timeout",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+388,0,"next_irq_pending",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+389,0,"do_waitirq",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+390,0,"alu_out",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+391,0,"alu_out_q",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+392,0,"alu_out_0",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+393,0,"alu_out_0_q",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+394,0,"alu_wait",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+395,0,"alu_wait_2",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+396,0,"alu_add_sub",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+397,0,"alu_shl",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+398,0,"alu_shr",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+399,0,"alu_eq",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+400,0,"alu_ltu",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+401,0,"alu_lts",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+402,0,"clear_prefetched_high_word_q",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+403,0,"cpuregs_write",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+404,0,"cpuregs_wrdata",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+405,0,"cpuregs_rs1",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+406,0,"cpuregs_rs2",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+407,0,"decoded_rs",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->popPrefix();
    tracep->popPrefix();
}

VL_ATTR_COLD void Vtop___024root__trace_init_sub__TOP__constants_pkg__0(Vtop___024root* vlSelf, VerilatedVcd* tracep) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_init_sub__TOP__constants_pkg__0\n"); );
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Body
    const int c = vlSymsp->__Vm_baseCode;
    tracep->declBus(c+432,0,"TOTAL_WORDS",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::INT, false,-1, 31,0);
    tracep->declBus(c+433,0,"ACCUM_WIDTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::INT, false,-1, 31,0);
    tracep->declBus(c+434,0,"WORD_WIDTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::INT, false,-1, 31,0);
}

VL_ATTR_COLD void Vtop___024root__trace_init_top(Vtop___024root* vlSelf, VerilatedVcd* tracep) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_init_top\n"); );
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Body
    Vtop___024root__trace_init_sub__TOP__0(vlSelf, tracep);
}

VL_ATTR_COLD void Vtop___024root__trace_const_0(void* voidSelf, VerilatedVcd::Buffer* bufp);
VL_ATTR_COLD void Vtop___024root__trace_full_0(void* voidSelf, VerilatedVcd::Buffer* bufp);
void Vtop___024root__trace_chg_0(void* voidSelf, VerilatedVcd::Buffer* bufp);
void Vtop___024root__trace_cleanup(void* voidSelf, VerilatedVcd* /*unused*/);

VL_ATTR_COLD void Vtop___024root__trace_register(Vtop___024root* vlSelf, VerilatedVcd* tracep) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_register\n"); );
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Body
    tracep->addConstCb(&Vtop___024root__trace_const_0, 0, vlSelf);
    tracep->addFullCb(&Vtop___024root__trace_full_0, 0, vlSelf);
    tracep->addChgCb(&Vtop___024root__trace_chg_0, 0, vlSelf);
    tracep->addCleanupCb(&Vtop___024root__trace_cleanup, vlSelf);
}

VL_ATTR_COLD void Vtop___024root__trace_const_0_sub_0(Vtop___024root* vlSelf, VerilatedVcd::Buffer* bufp);

VL_ATTR_COLD void Vtop___024root__trace_const_0(void* voidSelf, VerilatedVcd::Buffer* bufp) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_const_0\n"); );
    // Body
    Vtop___024root* const __restrict vlSelf VL_ATTR_UNUSED = static_cast<Vtop___024root*>(voidSelf);
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    Vtop___024root__trace_const_0_sub_0((&vlSymsp->TOP), bufp);
}

VL_ATTR_COLD void Vtop___024root__trace_const_0_sub_0(Vtop___024root* vlSelf, VerilatedVcd::Buffer* bufp) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_const_0_sub_0\n"); );
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Body
    uint32_t* const oldp VL_ATTR_UNUSED = bufp->oldp(vlSymsp->__Vm_baseCode);
    bufp->fullBit(oldp+408,(1U));
    bufp->fullBit(oldp+409,(0U));
    bufp->fullIData(oldp+410,(0U),32);
    bufp->fullIData(oldp+411,(0xffffffffU),32);
    bufp->fullIData(oldp+412,(0x00000010U),32);
    bufp->fullIData(oldp+413,(0U),32);
    bufp->fullIData(oldp+414,(1U),32);
    bufp->fullIData(oldp+415,(2U),32);
    bufp->fullIData(oldp+416,(0x00000020U),32);
    bufp->fullIData(oldp+417,(5U),32);
    bufp->fullQData(oldp+418,(0x0000000100000000ULL),36);
    bufp->fullQData(oldp+420,(0x0000000200000000ULL),36);
    bufp->fullQData(oldp+422,(0x0000000800000000ULL),36);
    bufp->fullCData(oldp+424,(0x80U),8);
    bufp->fullCData(oldp+425,(0x40U),8);
    bufp->fullCData(oldp+426,(0x20U),8);
    bufp->fullCData(oldp+427,(0x10U),8);
    bufp->fullCData(oldp+428,(8U),8);
    bufp->fullCData(oldp+429,(4U),8);
    bufp->fullCData(oldp+430,(2U),8);
    bufp->fullCData(oldp+431,(1U),8);
    bufp->fullIData(oldp+432,(8U),32);
    bufp->fullIData(oldp+433,(9U),32);
    bufp->fullIData(oldp+434,(3U),32);
}

VL_ATTR_COLD void Vtop___024root__trace_full_0_sub_0(Vtop___024root* vlSelf, VerilatedVcd::Buffer* bufp);

VL_ATTR_COLD void Vtop___024root__trace_full_0(void* voidSelf, VerilatedVcd::Buffer* bufp) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_full_0\n"); );
    // Body
    Vtop___024root* const __restrict vlSelf VL_ATTR_UNUSED = static_cast<Vtop___024root*>(voidSelf);
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    Vtop___024root__trace_full_0_sub_0((&vlSymsp->TOP), bufp);
}

VL_ATTR_COLD void Vtop___024root__trace_full_0_sub_0(Vtop___024root* vlSelf, VerilatedVcd::Buffer* bufp) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_full_0_sub_0\n"); );
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Body
    uint32_t* const oldp VL_ATTR_UNUSED = bufp->oldp(vlSymsp->__Vm_baseCode);
    bufp->fullBit(oldp+1,(vlSelfRef.clk));
    bufp->fullBit(oldp+2,(vlSelfRef.rst));
    bufp->fullBit(oldp+3,(vlSelfRef.trap));
    bufp->fullCData(oldp+4,(vlSelfRef.led),8);
    bufp->fullBit(oldp+5,(vlSelfRef.top_soc__DOT__clk));
    bufp->fullBit(oldp+6,(vlSelfRef.top_soc__DOT__rst));
    bufp->fullBit(oldp+7,(vlSelfRef.top_soc__DOT__trap));
    bufp->fullCData(oldp+8,(vlSelfRef.top_soc__DOT__led),8);
    bufp->fullBit(oldp+9,(vlSelfRef.top_soc__DOT__pcpi_valid));
    bufp->fullIData(oldp+10,(vlSelfRef.top_soc__DOT__pcpi_insn),32);
    bufp->fullIData(oldp+11,(vlSelfRef.top_soc__DOT__pcpi_rs1),32);
    bufp->fullIData(oldp+12,(vlSelfRef.top_soc__DOT__pcpi_rs2),32);
    bufp->fullBit(oldp+13,(vlSelfRef.top_soc__DOT__pcpi_wr));
    bufp->fullIData(oldp+14,(vlSelfRef.top_soc__DOT__pcpi_rd),32);
    bufp->fullBit(oldp+15,(vlSelfRef.top_soc__DOT__pcpi_wait));
    bufp->fullBit(oldp+16,(vlSelfRef.top_soc__DOT__pcpi_ready));
    bufp->fullBit(oldp+17,(vlSelfRef.top_soc__DOT__mem_valid));
    bufp->fullBit(oldp+18,(vlSelfRef.top_soc__DOT__mem_instr));
    bufp->fullBit(oldp+19,(vlSelfRef.top_soc__DOT__mem_ready));
    bufp->fullIData(oldp+20,(vlSelfRef.top_soc__DOT__mem_addr),32);
    bufp->fullIData(oldp+21,(vlSelfRef.top_soc__DOT__mem_wdata),32);
    bufp->fullCData(oldp+22,(vlSelfRef.top_soc__DOT__mem_wstrb),4);
    bufp->fullIData(oldp+23,(vlSelfRef.top_soc__DOT__mem_rdata),32);
    bufp->fullSData(oldp+24,(vlSelfRef.top_soc__DOT__bram_addr),14);
    bufp->fullBit(oldp+25,(vlSelfRef.top_soc__DOT__mem_ready_reg));
    bufp->fullCData(oldp+26,(vlSelfRef.top_soc__DOT__led_reg),8);
    bufp->fullBit(oldp+27,(vlSelfRef.top_soc__DOT__select_led));
    bufp->fullBit(oldp+28,(vlSelfRef.top_soc__DOT__select_inp_bram));
    bufp->fullBit(oldp+29,(vlSelfRef.top_soc__DOT__select_wt_bram));
    bufp->fullBit(oldp+30,(vlSelfRef.top_soc__DOT__select_bram));
    bufp->fullBit(oldp+31,(vlSelfRef.top_soc__DOT__select_bnn_axi));
    bufp->fullIData(oldp+32,(vlSelfRef.top_soc__DOT__inp_bram_addr),32);
    bufp->fullIData(oldp+33,(vlSelfRef.top_soc__DOT__inp_bram_dout),32);
    bufp->fullIData(oldp+34,(vlSelfRef.top_soc__DOT__wt_bram_addr),32);
    bufp->fullIData(oldp+35,(vlSelfRef.top_soc__DOT__wt_bram_dout),32);
    bufp->fullBit(oldp+36,(vlSelfRef.top_soc__DOT__axi_awready));
    bufp->fullBit(oldp+37,(vlSelfRef.top_soc__DOT__axi_wready));
    bufp->fullBit(oldp+38,(vlSelfRef.top_soc__DOT__axi_bvalid));
    bufp->fullBit(oldp+39,(vlSelfRef.top_soc__DOT__axi_arready));
    bufp->fullBit(oldp+40,(vlSelfRef.top_soc__DOT__axi_rvalid));
    bufp->fullIData(oldp+41,(vlSelfRef.top_soc__DOT__axi_rdata),32);
    bufp->fullBit(oldp+42,(vlSelfRef.top_soc__DOT__u_bnn_accelerator__DOT__aclk));
    bufp->fullBit(oldp+43,(vlSelfRef.top_soc__DOT__u_bnn_accelerator__DOT__aresetn));
    bufp->fullIData(oldp+44,(vlSelfRef.top_soc__DOT__u_bnn_accelerator__DOT__s_axi_awaddr),32);
    bufp->fullBit(oldp+45,(vlSelfRef.top_soc__DOT__u_bnn_accelerator__DOT__s_axi_awvalid));
    bufp->fullBit(oldp+46,(vlSelfRef.top_soc__DOT__u_bnn_accelerator__DOT__s_axi_awready));
    bufp->fullIData(oldp+47,(vlSelfRef.top_soc__DOT__u_bnn_accelerator__DOT__s_axi_wdata),32);
    bufp->fullBit(oldp+48,(vlSelfRef.top_soc__DOT__u_bnn_accelerator__DOT__s_axi_wvalid));
    bufp->fullBit(oldp+49,(vlSelfRef.top_soc__DOT__u_bnn_accelerator__DOT__s_axi_wready));
    bufp->fullBit(oldp+50,(vlSelfRef.top_soc__DOT__u_bnn_accelerator__DOT__s_axi_bvalid));
    bufp->fullBit(oldp+51,(vlSelfRef.top_soc__DOT__u_bnn_accelerator__DOT__s_axi_bready));
    bufp->fullIData(oldp+52,(vlSelfRef.top_soc__DOT__u_bnn_accelerator__DOT__s_axi_araddr),32);
    bufp->fullBit(oldp+53,(vlSelfRef.top_soc__DOT__u_bnn_accelerator__DOT__s_axi_arvalid));
    bufp->fullBit(oldp+54,(vlSelfRef.top_soc__DOT__u_bnn_accelerator__DOT__s_axi_arready));
    bufp->fullIData(oldp+55,(vlSelfRef.top_soc__DOT__u_bnn_accelerator__DOT__s_axi_rdata),32);
    bufp->fullBit(oldp+56,(vlSelfRef.top_soc__DOT__u_bnn_accelerator__DOT__s_axi_rvalid));
    bufp->fullBit(oldp+57,(vlSelfRef.top_soc__DOT__u_bnn_accelerator__DOT__s_axi_rready));
    bufp->fullCData(oldp+58,(vlSelfRef.top_soc__DOT__u_bnn_accelerator__DOT__s_axi_bresp),2);
    bufp->fullCData(oldp+59,(vlSelfRef.top_soc__DOT__u_bnn_accelerator__DOT__s_axi_rresp),2);
    bufp->fullIData(oldp+60,(vlSelfRef.top_soc__DOT__u_bnn_accelerator__DOT__inp_bram_addr),32);
    bufp->fullIData(oldp+61,(vlSelfRef.top_soc__DOT__u_bnn_accelerator__DOT__inp_bram_dout),32);
    bufp->fullIData(oldp+62,(vlSelfRef.top_soc__DOT__u_bnn_accelerator__DOT__wt_bram_addr),32);
    bufp->fullIData(oldp+63,(vlSelfRef.top_soc__DOT__u_bnn_accelerator__DOT__wt_bram_dout),32);
    bufp->fullIData(oldp+64,(vlSelfRef.top_soc__DOT__u_bnn_accelerator__DOT__ctrl_reg),32);
    bufp->fullIData(oldp+65,(vlSelfRef.top_soc__DOT__u_bnn_accelerator__DOT__in_ptr_reg),32);
    bufp->fullIData(oldp+66,(vlSelfRef.top_soc__DOT__u_bnn_accelerator__DOT__wt_ptr_reg),32);
    bufp->fullBit(oldp+67,(vlSelfRef.top_soc__DOT__u_bnn_accelerator__DOT__bnn_start));
    bufp->fullBit(oldp+68,(vlSelfRef.top_soc__DOT__u_bnn_accelerator__DOT__bnn_busy));
    bufp->fullBit(oldp+69,(vlSelfRef.top_soc__DOT__u_bnn_accelerator__DOT__bnn_done));
    bufp->fullIData(oldp+70,(vlSelfRef.top_soc__DOT__u_bnn_accelerator__DOT__bnn_result),32);
    bufp->fullBit(oldp+71,(vlSelfRef.top_soc__DOT__u_bnn_accelerator__DOT__aw_ready));
    bufp->fullBit(oldp+72,(vlSelfRef.top_soc__DOT__u_bnn_accelerator__DOT__w_ready));
    bufp->fullBit(oldp+73,(vlSelfRef.top_soc__DOT__u_bnn_accelerator__DOT__b_valid));
    bufp->fullBit(oldp+74,(vlSelfRef.top_soc__DOT__u_bnn_accelerator__DOT__ar_ready));
    bufp->fullBit(oldp+75,(vlSelfRef.top_soc__DOT__u_bnn_accelerator__DOT__r_valid));
    bufp->fullIData(oldp+76,(vlSelfRef.top_soc__DOT__u_bnn_accelerator__DOT__status_reg),32);
    bufp->fullIData(oldp+77,(vlSelfRef.top_soc__DOT__u_bnn_accelerator__DOT__addr_read),32);
    bufp->fullIData(oldp+78,(vlSelfRef.top_soc__DOT__u_bnn_accelerator__DOT__addr_write),32);
    bufp->fullBit(oldp+79,(vlSelfRef.top_soc__DOT__u_bnn_accelerator__DOT__i_bnn_core__DOT__clk));
    bufp->fullBit(oldp+80,(vlSelfRef.top_soc__DOT__u_bnn_accelerator__DOT__i_bnn_core__DOT__rstn));
    bufp->fullBit(oldp+81,(vlSelfRef.top_soc__DOT__u_bnn_accelerator__DOT__i_bnn_core__DOT__start));
    bufp->fullIData(oldp+82,(vlSelfRef.top_soc__DOT__u_bnn_accelerator__DOT__i_bnn_core__DOT__in_ptr),32);
    bufp->fullIData(oldp+83,(vlSelfRef.top_soc__DOT__u_bnn_accelerator__DOT__i_bnn_core__DOT__wt_ptr),32);
    bufp->fullIData(oldp+84,(vlSelfRef.top_soc__DOT__u_bnn_accelerator__DOT__i_bnn_core__DOT__inp_bram_addr),32);
    bufp->fullIData(oldp+85,(vlSelfRef.top_soc__DOT__u_bnn_accelerator__DOT__i_bnn_core__DOT__inp_bram_dout),32);
    bufp->fullIData(oldp+86,(vlSelfRef.top_soc__DOT__u_bnn_accelerator__DOT__i_bnn_core__DOT__wt_bram_addr),32);
    bufp->fullIData(oldp+87,(vlSelfRef.top_soc__DOT__u_bnn_accelerator__DOT__i_bnn_core__DOT__wt_bram_dout),32);
    bufp->fullBit(oldp+88,(vlSelfRef.top_soc__DOT__u_bnn_accelerator__DOT__i_bnn_core__DOT__busy));
    bufp->fullBit(oldp+89,(vlSelfRef.top_soc__DOT__u_bnn_accelerator__DOT__i_bnn_core__DOT__done));
    bufp->fullIData(oldp+90,(vlSelfRef.top_soc__DOT__u_bnn_accelerator__DOT__i_bnn_core__DOT__result),32);
    bufp->fullBit(oldp+91,(vlSelfRef.top_soc__DOT__u_bnn_accelerator__DOT__i_bnn_core__DOT__enable));
    bufp->fullBit(oldp+92,(vlSelfRef.top_soc__DOT__u_bnn_accelerator__DOT__i_bnn_core__DOT__clear_accumulator));
    bufp->fullSData(oldp+93,(vlSelfRef.top_soc__DOT__u_bnn_accelerator__DOT__i_bnn_core__DOT__pe_result),9);
    bufp->fullCData(oldp+94,(vlSelfRef.top_soc__DOT__u_bnn_accelerator__DOT__i_bnn_core__DOT__state),3);
    bufp->fullCData(oldp+95,(vlSelfRef.top_soc__DOT__u_bnn_accelerator__DOT__i_bnn_core__DOT__word_idx),3);
    bufp->fullIData(oldp+96,(vlSelfRef.top_soc__DOT__u_bnn_accelerator__DOT__i_bnn_core__DOT__offset_count),32);
    bufp->fullIData(oldp+97,(vlSelfRef.top_soc__DOT__u_bnn_accelerator__DOT__i_bnn_core__DOT__inputs_reg),32);
    bufp->fullIData(oldp+98,(vlSelfRef.top_soc__DOT__u_bnn_accelerator__DOT__i_bnn_core__DOT__weights_reg),32);
    bufp->fullBit(oldp+99,(vlSelfRef.top_soc__DOT__u_bnn_accelerator__DOT__i_bnn_core__DOT__pe__DOT__clk));
    bufp->fullBit(oldp+100,(vlSelfRef.top_soc__DOT__u_bnn_accelerator__DOT__i_bnn_core__DOT__pe__DOT__rstn));
    bufp->fullIData(oldp+101,(vlSelfRef.top_soc__DOT__u_bnn_accelerator__DOT__i_bnn_core__DOT__pe__DOT__input_register),32);
    bufp->fullIData(oldp+102,(vlSelfRef.top_soc__DOT__u_bnn_accelerator__DOT__i_bnn_core__DOT__pe__DOT__weight_register),32);
    bufp->fullSData(oldp+103,(vlSelfRef.top_soc__DOT__u_bnn_accelerator__DOT__i_bnn_core__DOT__pe__DOT__neuron_value),9);
    bufp->fullBit(oldp+104,(vlSelfRef.top_soc__DOT__u_bnn_accelerator__DOT__i_bnn_core__DOT__pe__DOT__enable));
    bufp->fullBit(oldp+105,(vlSelfRef.top_soc__DOT__u_bnn_accelerator__DOT__i_bnn_core__DOT__pe__DOT__clear_accumulator));
    bufp->fullIData(oldp+106,(vlSelfRef.top_soc__DOT__u_bnn_accelerator__DOT__i_bnn_core__DOT__pe__DOT__xnor_result),32);
    bufp->fullCData(oldp+107,(vlSelfRef.top_soc__DOT__u_bnn_accelerator__DOT__i_bnn_core__DOT__pe__DOT__stage1[0]),2);
    bufp->fullCData(oldp+108,(vlSelfRef.top_soc__DOT__u_bnn_accelerator__DOT__i_bnn_core__DOT__pe__DOT__stage1[1]),2);
    bufp->fullCData(oldp+109,(vlSelfRef.top_soc__DOT__u_bnn_accelerator__DOT__i_bnn_core__DOT__pe__DOT__stage1[2]),2);
    bufp->fullCData(oldp+110,(vlSelfRef.top_soc__DOT__u_bnn_accelerator__DOT__i_bnn_core__DOT__pe__DOT__stage1[3]),2);
    bufp->fullCData(oldp+111,(vlSelfRef.top_soc__DOT__u_bnn_accelerator__DOT__i_bnn_core__DOT__pe__DOT__stage1[4]),2);
    bufp->fullCData(oldp+112,(vlSelfRef.top_soc__DOT__u_bnn_accelerator__DOT__i_bnn_core__DOT__pe__DOT__stage1[5]),2);
    bufp->fullCData(oldp+113,(vlSelfRef.top_soc__DOT__u_bnn_accelerator__DOT__i_bnn_core__DOT__pe__DOT__stage1[6]),2);
    bufp->fullCData(oldp+114,(vlSelfRef.top_soc__DOT__u_bnn_accelerator__DOT__i_bnn_core__DOT__pe__DOT__stage1[7]),2);
    bufp->fullCData(oldp+115,(vlSelfRef.top_soc__DOT__u_bnn_accelerator__DOT__i_bnn_core__DOT__pe__DOT__stage1[8]),2);
    bufp->fullCData(oldp+116,(vlSelfRef.top_soc__DOT__u_bnn_accelerator__DOT__i_bnn_core__DOT__pe__DOT__stage1[9]),2);
    bufp->fullCData(oldp+117,(vlSelfRef.top_soc__DOT__u_bnn_accelerator__DOT__i_bnn_core__DOT__pe__DOT__stage1[10]),2);
    bufp->fullCData(oldp+118,(vlSelfRef.top_soc__DOT__u_bnn_accelerator__DOT__i_bnn_core__DOT__pe__DOT__stage1[11]),2);
    bufp->fullCData(oldp+119,(vlSelfRef.top_soc__DOT__u_bnn_accelerator__DOT__i_bnn_core__DOT__pe__DOT__stage1[12]),2);
    bufp->fullCData(oldp+120,(vlSelfRef.top_soc__DOT__u_bnn_accelerator__DOT__i_bnn_core__DOT__pe__DOT__stage1[13]),2);
    bufp->fullCData(oldp+121,(vlSelfRef.top_soc__DOT__u_bnn_accelerator__DOT__i_bnn_core__DOT__pe__DOT__stage1[14]),2);
    bufp->fullCData(oldp+122,(vlSelfRef.top_soc__DOT__u_bnn_accelerator__DOT__i_bnn_core__DOT__pe__DOT__stage1[15]),2);
    bufp->fullCData(oldp+123,(vlSelfRef.top_soc__DOT__u_bnn_accelerator__DOT__i_bnn_core__DOT__pe__DOT__stage2[0]),3);
    bufp->fullCData(oldp+124,(vlSelfRef.top_soc__DOT__u_bnn_accelerator__DOT__i_bnn_core__DOT__pe__DOT__stage2[1]),3);
    bufp->fullCData(oldp+125,(vlSelfRef.top_soc__DOT__u_bnn_accelerator__DOT__i_bnn_core__DOT__pe__DOT__stage2[2]),3);
    bufp->fullCData(oldp+126,(vlSelfRef.top_soc__DOT__u_bnn_accelerator__DOT__i_bnn_core__DOT__pe__DOT__stage2[3]),3);
    bufp->fullCData(oldp+127,(vlSelfRef.top_soc__DOT__u_bnn_accelerator__DOT__i_bnn_core__DOT__pe__DOT__stage2[4]),3);
    bufp->fullCData(oldp+128,(vlSelfRef.top_soc__DOT__u_bnn_accelerator__DOT__i_bnn_core__DOT__pe__DOT__stage2[5]),3);
    bufp->fullCData(oldp+129,(vlSelfRef.top_soc__DOT__u_bnn_accelerator__DOT__i_bnn_core__DOT__pe__DOT__stage2[6]),3);
    bufp->fullCData(oldp+130,(vlSelfRef.top_soc__DOT__u_bnn_accelerator__DOT__i_bnn_core__DOT__pe__DOT__stage2[7]),3);
    bufp->fullCData(oldp+131,(vlSelfRef.top_soc__DOT__u_bnn_accelerator__DOT__i_bnn_core__DOT__pe__DOT__stage3[0]),4);
    bufp->fullCData(oldp+132,(vlSelfRef.top_soc__DOT__u_bnn_accelerator__DOT__i_bnn_core__DOT__pe__DOT__stage3[1]),4);
    bufp->fullCData(oldp+133,(vlSelfRef.top_soc__DOT__u_bnn_accelerator__DOT__i_bnn_core__DOT__pe__DOT__stage3[2]),4);
    bufp->fullCData(oldp+134,(vlSelfRef.top_soc__DOT__u_bnn_accelerator__DOT__i_bnn_core__DOT__pe__DOT__stage3[3]),4);
    bufp->fullCData(oldp+135,(vlSelfRef.top_soc__DOT__u_bnn_accelerator__DOT__i_bnn_core__DOT__pe__DOT__stage4[0]),5);
    bufp->fullCData(oldp+136,(vlSelfRef.top_soc__DOT__u_bnn_accelerator__DOT__i_bnn_core__DOT__pe__DOT__stage4[1]),5);
    bufp->fullIData(oldp+137,(vlSelfRef.top_soc__DOT__u_bnn_accelerator__DOT__i_bnn_core__DOT__pe__DOT__i),32);
    bufp->fullCData(oldp+138,(vlSelfRef.top_soc__DOT__u_bnn_accelerator__DOT__i_bnn_core__DOT__pe__DOT__sum_reg),6);
    bufp->fullIData(oldp+139,(vlSelfRef.top_soc__DOT__u_bnn_accelerator__DOT__i_bnn_core__DOT__pe__DOT__inp),32);
    bufp->fullIData(oldp+140,(vlSelfRef.top_soc__DOT__u_bnn_accelerator__DOT__i_bnn_core__DOT__pe__DOT__wt),32);
    bufp->fullSData(oldp+141,(vlSelfRef.top_soc__DOT__u_bnn_accelerator__DOT__i_bnn_core__DOT__pe__DOT__accumulator),9);
    bufp->fullBit(oldp+142,(vlSelfRef.top_soc__DOT__uut__DOT__clk));
    bufp->fullBit(oldp+143,(vlSelfRef.top_soc__DOT__uut__DOT__resetn));
    bufp->fullBit(oldp+144,(vlSelfRef.top_soc__DOT__uut__DOT__trap));
    bufp->fullBit(oldp+145,(vlSelfRef.top_soc__DOT__uut__DOT__mem_valid));
    bufp->fullBit(oldp+146,(vlSelfRef.top_soc__DOT__uut__DOT__mem_instr));
    bufp->fullBit(oldp+147,(vlSelfRef.top_soc__DOT__uut__DOT__mem_ready));
    bufp->fullIData(oldp+148,(vlSelfRef.top_soc__DOT__uut__DOT__mem_addr),32);
    bufp->fullIData(oldp+149,(vlSelfRef.top_soc__DOT__uut__DOT__mem_wdata),32);
    bufp->fullCData(oldp+150,(vlSelfRef.top_soc__DOT__uut__DOT__mem_wstrb),4);
    bufp->fullIData(oldp+151,(vlSelfRef.top_soc__DOT__uut__DOT__mem_rdata),32);
    bufp->fullBit(oldp+152,(vlSelfRef.top_soc__DOT__uut__DOT__mem_la_read));
    bufp->fullBit(oldp+153,(vlSelfRef.top_soc__DOT__uut__DOT__mem_la_write));
    bufp->fullIData(oldp+154,(vlSelfRef.top_soc__DOT__uut__DOT__mem_la_addr),32);
    bufp->fullIData(oldp+155,(vlSelfRef.top_soc__DOT__uut__DOT__mem_la_wdata),32);
    bufp->fullCData(oldp+156,(vlSelfRef.top_soc__DOT__uut__DOT__mem_la_wstrb),4);
    bufp->fullBit(oldp+157,(vlSelfRef.top_soc__DOT__uut__DOT__pcpi_valid));
    bufp->fullIData(oldp+158,(vlSelfRef.top_soc__DOT__uut__DOT__pcpi_insn),32);
    bufp->fullIData(oldp+159,(vlSelfRef.top_soc__DOT__uut__DOT__pcpi_rs1),32);
    bufp->fullIData(oldp+160,(vlSelfRef.top_soc__DOT__uut__DOT__pcpi_rs2),32);
    bufp->fullBit(oldp+161,(vlSelfRef.top_soc__DOT__uut__DOT__pcpi_wr));
    bufp->fullIData(oldp+162,(vlSelfRef.top_soc__DOT__uut__DOT__pcpi_rd),32);
    bufp->fullBit(oldp+163,(vlSelfRef.top_soc__DOT__uut__DOT__pcpi_wait));
    bufp->fullBit(oldp+164,(vlSelfRef.top_soc__DOT__uut__DOT__pcpi_ready));
    bufp->fullIData(oldp+165,(vlSelfRef.top_soc__DOT__uut__DOT__irq),32);
    bufp->fullIData(oldp+166,(vlSelfRef.top_soc__DOT__uut__DOT__eoi),32);
    bufp->fullBit(oldp+167,(vlSelfRef.top_soc__DOT__uut__DOT__trace_valid));
    bufp->fullQData(oldp+168,(vlSelfRef.top_soc__DOT__uut__DOT__trace_data),36);
    bufp->fullQData(oldp+170,(vlSelfRef.top_soc__DOT__uut__DOT__count_cycle),64);
    bufp->fullQData(oldp+172,(vlSelfRef.top_soc__DOT__uut__DOT__count_instr),64);
    bufp->fullIData(oldp+174,(vlSelfRef.top_soc__DOT__uut__DOT__reg_pc),32);
    bufp->fullIData(oldp+175,(vlSelfRef.top_soc__DOT__uut__DOT__reg_next_pc),32);
    bufp->fullIData(oldp+176,(vlSelfRef.top_soc__DOT__uut__DOT__reg_op1),32);
    bufp->fullIData(oldp+177,(vlSelfRef.top_soc__DOT__uut__DOT__reg_op2),32);
    bufp->fullIData(oldp+178,(vlSelfRef.top_soc__DOT__uut__DOT__reg_out),32);
    bufp->fullCData(oldp+179,(vlSelfRef.top_soc__DOT__uut__DOT__reg_sh),5);
    bufp->fullIData(oldp+180,(vlSelfRef.top_soc__DOT__uut__DOT__next_insn_opcode),32);
    bufp->fullIData(oldp+181,(vlSelfRef.top_soc__DOT__uut__DOT__dbg_insn_opcode),32);
    bufp->fullIData(oldp+182,(vlSelfRef.top_soc__DOT__uut__DOT__dbg_insn_addr),32);
    bufp->fullBit(oldp+183,(vlSelfRef.top_soc__DOT__uut__DOT__dbg_mem_valid));
    bufp->fullBit(oldp+184,(vlSelfRef.top_soc__DOT__uut__DOT__dbg_mem_instr));
    bufp->fullBit(oldp+185,(vlSelfRef.top_soc__DOT__uut__DOT__dbg_mem_ready));
    bufp->fullIData(oldp+186,(vlSelfRef.top_soc__DOT__uut__DOT__dbg_mem_addr),32);
    bufp->fullIData(oldp+187,(vlSelfRef.top_soc__DOT__uut__DOT__dbg_mem_wdata),32);
    bufp->fullCData(oldp+188,(vlSelfRef.top_soc__DOT__uut__DOT__dbg_mem_wstrb),4);
    bufp->fullIData(oldp+189,(vlSelfRef.top_soc__DOT__uut__DOT__dbg_mem_rdata),32);
    bufp->fullIData(oldp+190,(vlSelfRef.top_soc__DOT__uut__DOT__next_pc),32);
    bufp->fullBit(oldp+191,(vlSelfRef.top_soc__DOT__uut__DOT__irq_delay));
    bufp->fullBit(oldp+192,(vlSelfRef.top_soc__DOT__uut__DOT__irq_active));
    bufp->fullIData(oldp+193,(vlSelfRef.top_soc__DOT__uut__DOT__irq_mask),32);
    bufp->fullIData(oldp+194,(vlSelfRef.top_soc__DOT__uut__DOT__irq_pending),32);
    bufp->fullIData(oldp+195,(vlSelfRef.top_soc__DOT__uut__DOT__timer),32);
    bufp->fullIData(oldp+196,(vlSelfRef.top_soc__DOT__uut__DOT__cpuregs[0]),32);
    bufp->fullIData(oldp+197,(vlSelfRef.top_soc__DOT__uut__DOT__cpuregs[1]),32);
    bufp->fullIData(oldp+198,(vlSelfRef.top_soc__DOT__uut__DOT__cpuregs[2]),32);
    bufp->fullIData(oldp+199,(vlSelfRef.top_soc__DOT__uut__DOT__cpuregs[3]),32);
    bufp->fullIData(oldp+200,(vlSelfRef.top_soc__DOT__uut__DOT__cpuregs[4]),32);
    bufp->fullIData(oldp+201,(vlSelfRef.top_soc__DOT__uut__DOT__cpuregs[5]),32);
    bufp->fullIData(oldp+202,(vlSelfRef.top_soc__DOT__uut__DOT__cpuregs[6]),32);
    bufp->fullIData(oldp+203,(vlSelfRef.top_soc__DOT__uut__DOT__cpuregs[7]),32);
    bufp->fullIData(oldp+204,(vlSelfRef.top_soc__DOT__uut__DOT__cpuregs[8]),32);
    bufp->fullIData(oldp+205,(vlSelfRef.top_soc__DOT__uut__DOT__cpuregs[9]),32);
    bufp->fullIData(oldp+206,(vlSelfRef.top_soc__DOT__uut__DOT__cpuregs[10]),32);
    bufp->fullIData(oldp+207,(vlSelfRef.top_soc__DOT__uut__DOT__cpuregs[11]),32);
    bufp->fullIData(oldp+208,(vlSelfRef.top_soc__DOT__uut__DOT__cpuregs[12]),32);
    bufp->fullIData(oldp+209,(vlSelfRef.top_soc__DOT__uut__DOT__cpuregs[13]),32);
    bufp->fullIData(oldp+210,(vlSelfRef.top_soc__DOT__uut__DOT__cpuregs[14]),32);
    bufp->fullIData(oldp+211,(vlSelfRef.top_soc__DOT__uut__DOT__cpuregs[15]),32);
    bufp->fullIData(oldp+212,(vlSelfRef.top_soc__DOT__uut__DOT__cpuregs[16]),32);
    bufp->fullIData(oldp+213,(vlSelfRef.top_soc__DOT__uut__DOT__cpuregs[17]),32);
    bufp->fullIData(oldp+214,(vlSelfRef.top_soc__DOT__uut__DOT__cpuregs[18]),32);
    bufp->fullIData(oldp+215,(vlSelfRef.top_soc__DOT__uut__DOT__cpuregs[19]),32);
    bufp->fullIData(oldp+216,(vlSelfRef.top_soc__DOT__uut__DOT__cpuregs[20]),32);
    bufp->fullIData(oldp+217,(vlSelfRef.top_soc__DOT__uut__DOT__cpuregs[21]),32);
    bufp->fullIData(oldp+218,(vlSelfRef.top_soc__DOT__uut__DOT__cpuregs[22]),32);
    bufp->fullIData(oldp+219,(vlSelfRef.top_soc__DOT__uut__DOT__cpuregs[23]),32);
    bufp->fullIData(oldp+220,(vlSelfRef.top_soc__DOT__uut__DOT__cpuregs[24]),32);
    bufp->fullIData(oldp+221,(vlSelfRef.top_soc__DOT__uut__DOT__cpuregs[25]),32);
    bufp->fullIData(oldp+222,(vlSelfRef.top_soc__DOT__uut__DOT__cpuregs[26]),32);
    bufp->fullIData(oldp+223,(vlSelfRef.top_soc__DOT__uut__DOT__cpuregs[27]),32);
    bufp->fullIData(oldp+224,(vlSelfRef.top_soc__DOT__uut__DOT__cpuregs[28]),32);
    bufp->fullIData(oldp+225,(vlSelfRef.top_soc__DOT__uut__DOT__cpuregs[29]),32);
    bufp->fullIData(oldp+226,(vlSelfRef.top_soc__DOT__uut__DOT__cpuregs[30]),32);
    bufp->fullIData(oldp+227,(vlSelfRef.top_soc__DOT__uut__DOT__cpuregs[31]),32);
    bufp->fullIData(oldp+228,(vlSelfRef.top_soc__DOT__uut__DOT__i),32);
    bufp->fullBit(oldp+229,(vlSelfRef.top_soc__DOT__uut__DOT__pcpi_mul_wr));
    bufp->fullIData(oldp+230,(vlSelfRef.top_soc__DOT__uut__DOT__pcpi_mul_rd),32);
    bufp->fullBit(oldp+231,(vlSelfRef.top_soc__DOT__uut__DOT__pcpi_mul_wait));
    bufp->fullBit(oldp+232,(vlSelfRef.top_soc__DOT__uut__DOT__pcpi_mul_ready));
    bufp->fullBit(oldp+233,(vlSelfRef.top_soc__DOT__uut__DOT__pcpi_div_wr));
    bufp->fullIData(oldp+234,(vlSelfRef.top_soc__DOT__uut__DOT__pcpi_div_rd),32);
    bufp->fullBit(oldp+235,(vlSelfRef.top_soc__DOT__uut__DOT__pcpi_div_wait));
    bufp->fullBit(oldp+236,(vlSelfRef.top_soc__DOT__uut__DOT__pcpi_div_ready));
    bufp->fullBit(oldp+237,(vlSelfRef.top_soc__DOT__uut__DOT__pcpi_int_wr));
    bufp->fullIData(oldp+238,(vlSelfRef.top_soc__DOT__uut__DOT__pcpi_int_rd),32);
    bufp->fullBit(oldp+239,(vlSelfRef.top_soc__DOT__uut__DOT__pcpi_int_wait));
    bufp->fullBit(oldp+240,(vlSelfRef.top_soc__DOT__uut__DOT__pcpi_int_ready));
    bufp->fullCData(oldp+241,(vlSelfRef.top_soc__DOT__uut__DOT__mem_state),2);
    bufp->fullCData(oldp+242,(vlSelfRef.top_soc__DOT__uut__DOT__mem_wordsize),2);
    bufp->fullIData(oldp+243,(vlSelfRef.top_soc__DOT__uut__DOT__mem_rdata_word),32);
    bufp->fullIData(oldp+244,(vlSelfRef.top_soc__DOT__uut__DOT__mem_rdata_q),32);
    bufp->fullBit(oldp+245,(vlSelfRef.top_soc__DOT__uut__DOT__mem_do_prefetch));
    bufp->fullBit(oldp+246,(vlSelfRef.top_soc__DOT__uut__DOT__mem_do_rinst));
    bufp->fullBit(oldp+247,(vlSelfRef.top_soc__DOT__uut__DOT__mem_do_rdata));
    bufp->fullBit(oldp+248,(vlSelfRef.top_soc__DOT__uut__DOT__mem_do_wdata));
    bufp->fullBit(oldp+249,(vlSelfRef.top_soc__DOT__uut__DOT__mem_xfer));
    bufp->fullBit(oldp+250,(vlSelfRef.top_soc__DOT__uut__DOT__mem_la_secondword));
    bufp->fullBit(oldp+251,(vlSelfRef.top_soc__DOT__uut__DOT__mem_la_firstword_reg));
    bufp->fullBit(oldp+252,(vlSelfRef.top_soc__DOT__uut__DOT__last_mem_valid));
    bufp->fullBit(oldp+253,(vlSelfRef.top_soc__DOT__uut__DOT__mem_la_firstword));
    bufp->fullBit(oldp+254,(vlSelfRef.top_soc__DOT__uut__DOT__mem_la_firstword_xfer));
    bufp->fullBit(oldp+255,(vlSelfRef.top_soc__DOT__uut__DOT__prefetched_high_word));
    bufp->fullBit(oldp+256,(vlSelfRef.top_soc__DOT__uut__DOT__clear_prefetched_high_word));
    bufp->fullSData(oldp+257,(vlSelfRef.top_soc__DOT__uut__DOT__mem_16bit_buffer),16);
    bufp->fullIData(oldp+258,(vlSelfRef.top_soc__DOT__uut__DOT__mem_rdata_latched_noshuffle),32);
    bufp->fullIData(oldp+259,(vlSelfRef.top_soc__DOT__uut__DOT__mem_rdata_latched),32);
    bufp->fullBit(oldp+260,(vlSelfRef.top_soc__DOT__uut__DOT__mem_la_use_prefetched_high_word));
    bufp->fullBit(oldp+261,(vlSelfRef.top_soc__DOT__uut__DOT__mem_busy));
    bufp->fullBit(oldp+262,(vlSelfRef.top_soc__DOT__uut__DOT__mem_done));
    bufp->fullBit(oldp+263,(vlSelfRef.top_soc__DOT__uut__DOT__instr_lui));
    bufp->fullBit(oldp+264,(vlSelfRef.top_soc__DOT__uut__DOT__instr_auipc));
    bufp->fullBit(oldp+265,(vlSelfRef.top_soc__DOT__uut__DOT__instr_jal));
    bufp->fullBit(oldp+266,(vlSelfRef.top_soc__DOT__uut__DOT__instr_jalr));
    bufp->fullBit(oldp+267,(vlSelfRef.top_soc__DOT__uut__DOT__instr_beq));
    bufp->fullBit(oldp+268,(vlSelfRef.top_soc__DOT__uut__DOT__instr_bne));
    bufp->fullBit(oldp+269,(vlSelfRef.top_soc__DOT__uut__DOT__instr_blt));
    bufp->fullBit(oldp+270,(vlSelfRef.top_soc__DOT__uut__DOT__instr_bge));
    bufp->fullBit(oldp+271,(vlSelfRef.top_soc__DOT__uut__DOT__instr_bltu));
    bufp->fullBit(oldp+272,(vlSelfRef.top_soc__DOT__uut__DOT__instr_bgeu));
    bufp->fullBit(oldp+273,(vlSelfRef.top_soc__DOT__uut__DOT__instr_lb));
    bufp->fullBit(oldp+274,(vlSelfRef.top_soc__DOT__uut__DOT__instr_lh));
    bufp->fullBit(oldp+275,(vlSelfRef.top_soc__DOT__uut__DOT__instr_lw));
    bufp->fullBit(oldp+276,(vlSelfRef.top_soc__DOT__uut__DOT__instr_lbu));
    bufp->fullBit(oldp+277,(vlSelfRef.top_soc__DOT__uut__DOT__instr_lhu));
    bufp->fullBit(oldp+278,(vlSelfRef.top_soc__DOT__uut__DOT__instr_sb));
    bufp->fullBit(oldp+279,(vlSelfRef.top_soc__DOT__uut__DOT__instr_sh));
    bufp->fullBit(oldp+280,(vlSelfRef.top_soc__DOT__uut__DOT__instr_sw));
    bufp->fullBit(oldp+281,(vlSelfRef.top_soc__DOT__uut__DOT__instr_addi));
    bufp->fullBit(oldp+282,(vlSelfRef.top_soc__DOT__uut__DOT__instr_slti));
    bufp->fullBit(oldp+283,(vlSelfRef.top_soc__DOT__uut__DOT__instr_sltiu));
    bufp->fullBit(oldp+284,(vlSelfRef.top_soc__DOT__uut__DOT__instr_xori));
    bufp->fullBit(oldp+285,(vlSelfRef.top_soc__DOT__uut__DOT__instr_ori));
    bufp->fullBit(oldp+286,(vlSelfRef.top_soc__DOT__uut__DOT__instr_andi));
    bufp->fullBit(oldp+287,(vlSelfRef.top_soc__DOT__uut__DOT__instr_slli));
    bufp->fullBit(oldp+288,(vlSelfRef.top_soc__DOT__uut__DOT__instr_srli));
    bufp->fullBit(oldp+289,(vlSelfRef.top_soc__DOT__uut__DOT__instr_srai));
    bufp->fullBit(oldp+290,(vlSelfRef.top_soc__DOT__uut__DOT__instr_add));
    bufp->fullBit(oldp+291,(vlSelfRef.top_soc__DOT__uut__DOT__instr_sub));
    bufp->fullBit(oldp+292,(vlSelfRef.top_soc__DOT__uut__DOT__instr_sll));
    bufp->fullBit(oldp+293,(vlSelfRef.top_soc__DOT__uut__DOT__instr_slt));
    bufp->fullBit(oldp+294,(vlSelfRef.top_soc__DOT__uut__DOT__instr_sltu));
    bufp->fullBit(oldp+295,(vlSelfRef.top_soc__DOT__uut__DOT__instr_xor));
    bufp->fullBit(oldp+296,(vlSelfRef.top_soc__DOT__uut__DOT__instr_srl));
    bufp->fullBit(oldp+297,(vlSelfRef.top_soc__DOT__uut__DOT__instr_sra));
    bufp->fullBit(oldp+298,(vlSelfRef.top_soc__DOT__uut__DOT__instr_or));
    bufp->fullBit(oldp+299,(vlSelfRef.top_soc__DOT__uut__DOT__instr_and));
    bufp->fullBit(oldp+300,(vlSelfRef.top_soc__DOT__uut__DOT__instr_rdcycle));
    bufp->fullBit(oldp+301,(vlSelfRef.top_soc__DOT__uut__DOT__instr_rdcycleh));
    bufp->fullBit(oldp+302,(vlSelfRef.top_soc__DOT__uut__DOT__instr_rdinstr));
    bufp->fullBit(oldp+303,(vlSelfRef.top_soc__DOT__uut__DOT__instr_rdinstrh));
    bufp->fullBit(oldp+304,(vlSelfRef.top_soc__DOT__uut__DOT__instr_ecall_ebreak));
    bufp->fullBit(oldp+305,(vlSelfRef.top_soc__DOT__uut__DOT__instr_fence));
    bufp->fullBit(oldp+306,(vlSelfRef.top_soc__DOT__uut__DOT__instr_getq));
    bufp->fullBit(oldp+307,(vlSelfRef.top_soc__DOT__uut__DOT__instr_setq));
    bufp->fullBit(oldp+308,(vlSelfRef.top_soc__DOT__uut__DOT__instr_retirq));
    bufp->fullBit(oldp+309,(vlSelfRef.top_soc__DOT__uut__DOT__instr_maskirq));
    bufp->fullBit(oldp+310,(vlSelfRef.top_soc__DOT__uut__DOT__instr_waitirq));
    bufp->fullBit(oldp+311,(vlSelfRef.top_soc__DOT__uut__DOT__instr_timer));
    bufp->fullBit(oldp+312,(vlSelfRef.top_soc__DOT__uut__DOT__instr_trap));
    bufp->fullCData(oldp+313,(vlSelfRef.top_soc__DOT__uut__DOT__decoded_rd),5);
    bufp->fullCData(oldp+314,(vlSelfRef.top_soc__DOT__uut__DOT__decoded_rs1),5);
    bufp->fullCData(oldp+315,(vlSelfRef.top_soc__DOT__uut__DOT__decoded_rs2),5);
    bufp->fullIData(oldp+316,(vlSelfRef.top_soc__DOT__uut__DOT__decoded_imm),32);
    bufp->fullIData(oldp+317,(vlSelfRef.top_soc__DOT__uut__DOT__decoded_imm_j),32);
    bufp->fullBit(oldp+318,(vlSelfRef.top_soc__DOT__uut__DOT__decoder_trigger));
    bufp->fullBit(oldp+319,(vlSelfRef.top_soc__DOT__uut__DOT__decoder_trigger_q));
    bufp->fullBit(oldp+320,(vlSelfRef.top_soc__DOT__uut__DOT__decoder_pseudo_trigger));
    bufp->fullBit(oldp+321,(vlSelfRef.top_soc__DOT__uut__DOT__decoder_pseudo_trigger_q));
    bufp->fullBit(oldp+322,(vlSelfRef.top_soc__DOT__uut__DOT__compressed_instr));
    bufp->fullBit(oldp+323,(vlSelfRef.top_soc__DOT__uut__DOT__is_lui_auipc_jal));
    bufp->fullBit(oldp+324,(vlSelfRef.top_soc__DOT__uut__DOT__is_lb_lh_lw_lbu_lhu));
    bufp->fullBit(oldp+325,(vlSelfRef.top_soc__DOT__uut__DOT__is_slli_srli_srai));
    bufp->fullBit(oldp+326,(vlSelfRef.top_soc__DOT__uut__DOT__is_jalr_addi_slti_sltiu_xori_ori_andi));
    bufp->fullBit(oldp+327,(vlSelfRef.top_soc__DOT__uut__DOT__is_sb_sh_sw));
    bufp->fullBit(oldp+328,(vlSelfRef.top_soc__DOT__uut__DOT__is_sll_srl_sra));
    bufp->fullBit(oldp+329,(vlSelfRef.top_soc__DOT__uut__DOT__is_lui_auipc_jal_jalr_addi_add_sub));
    bufp->fullBit(oldp+330,(vlSelfRef.top_soc__DOT__uut__DOT__is_slti_blt_slt));
    bufp->fullBit(oldp+331,(vlSelfRef.top_soc__DOT__uut__DOT__is_sltiu_bltu_sltu));
    bufp->fullBit(oldp+332,(vlSelfRef.top_soc__DOT__uut__DOT__is_beq_bne_blt_bge_bltu_bgeu));
    bufp->fullBit(oldp+333,(vlSelfRef.top_soc__DOT__uut__DOT__is_lbu_lhu_lw));
    bufp->fullBit(oldp+334,(vlSelfRef.top_soc__DOT__uut__DOT__is_alu_reg_imm));
    bufp->fullBit(oldp+335,(vlSelfRef.top_soc__DOT__uut__DOT__is_alu_reg_reg));
    bufp->fullBit(oldp+336,(vlSelfRef.top_soc__DOT__uut__DOT__is_compare));
    bufp->fullBit(oldp+337,(vlSelfRef.top_soc__DOT__uut__DOT__is_rdcycle_rdcycleh_rdinstr_rdinstrh));
    bufp->fullQData(oldp+338,(vlSelfRef.top_soc__DOT__uut__DOT__new_ascii_instr),64);
    bufp->fullQData(oldp+340,(vlSelfRef.top_soc__DOT__uut__DOT__dbg_ascii_instr),64);
    bufp->fullIData(oldp+342,(vlSelfRef.top_soc__DOT__uut__DOT__dbg_insn_imm),32);
    bufp->fullCData(oldp+343,(vlSelfRef.top_soc__DOT__uut__DOT__dbg_insn_rs1),5);
    bufp->fullCData(oldp+344,(vlSelfRef.top_soc__DOT__uut__DOT__dbg_insn_rs2),5);
    bufp->fullCData(oldp+345,(vlSelfRef.top_soc__DOT__uut__DOT__dbg_insn_rd),5);
    bufp->fullIData(oldp+346,(vlSelfRef.top_soc__DOT__uut__DOT__dbg_rs1val),32);
    bufp->fullIData(oldp+347,(vlSelfRef.top_soc__DOT__uut__DOT__dbg_rs2val),32);
    bufp->fullBit(oldp+348,(vlSelfRef.top_soc__DOT__uut__DOT__dbg_rs1val_valid));
    bufp->fullBit(oldp+349,(vlSelfRef.top_soc__DOT__uut__DOT__dbg_rs2val_valid));
    bufp->fullQData(oldp+350,(vlSelfRef.top_soc__DOT__uut__DOT__q_ascii_instr),64);
    bufp->fullIData(oldp+352,(vlSelfRef.top_soc__DOT__uut__DOT__q_insn_imm),32);
    bufp->fullIData(oldp+353,(vlSelfRef.top_soc__DOT__uut__DOT__q_insn_opcode),32);
    bufp->fullCData(oldp+354,(vlSelfRef.top_soc__DOT__uut__DOT__q_insn_rs1),5);
    bufp->fullCData(oldp+355,(vlSelfRef.top_soc__DOT__uut__DOT__q_insn_rs2),5);
    bufp->fullCData(oldp+356,(vlSelfRef.top_soc__DOT__uut__DOT__q_insn_rd),5);
    bufp->fullBit(oldp+357,(vlSelfRef.top_soc__DOT__uut__DOT__dbg_next));
    bufp->fullBit(oldp+358,(vlSelfRef.top_soc__DOT__uut__DOT__launch_next_insn));
    bufp->fullBit(oldp+359,(vlSelfRef.top_soc__DOT__uut__DOT__dbg_valid_insn));
    bufp->fullQData(oldp+360,(vlSelfRef.top_soc__DOT__uut__DOT__cached_ascii_instr),64);
    bufp->fullIData(oldp+362,(vlSelfRef.top_soc__DOT__uut__DOT__cached_insn_imm),32);
    bufp->fullIData(oldp+363,(vlSelfRef.top_soc__DOT__uut__DOT__cached_insn_opcode),32);
    bufp->fullCData(oldp+364,(vlSelfRef.top_soc__DOT__uut__DOT__cached_insn_rs1),5);
    bufp->fullCData(oldp+365,(vlSelfRef.top_soc__DOT__uut__DOT__cached_insn_rs2),5);
    bufp->fullCData(oldp+366,(vlSelfRef.top_soc__DOT__uut__DOT__cached_insn_rd),5);
    bufp->fullCData(oldp+367,(vlSelfRef.top_soc__DOT__uut__DOT__cpu_state),8);
    bufp->fullCData(oldp+368,(vlSelfRef.top_soc__DOT__uut__DOT__irq_state),2);
    bufp->fullWData(oldp+369,(vlSelfRef.top_soc__DOT__uut__DOT__dbg_ascii_state),128);
    bufp->fullBit(oldp+373,(vlSelfRef.top_soc__DOT__uut__DOT__set_mem_do_rinst));
    bufp->fullBit(oldp+374,(vlSelfRef.top_soc__DOT__uut__DOT__set_mem_do_rdata));
    bufp->fullBit(oldp+375,(vlSelfRef.top_soc__DOT__uut__DOT__set_mem_do_wdata));
    bufp->fullBit(oldp+376,(vlSelfRef.top_soc__DOT__uut__DOT__latched_store));
    bufp->fullBit(oldp+377,(vlSelfRef.top_soc__DOT__uut__DOT__latched_stalu));
    bufp->fullBit(oldp+378,(vlSelfRef.top_soc__DOT__uut__DOT__latched_branch));
    bufp->fullBit(oldp+379,(vlSelfRef.top_soc__DOT__uut__DOT__latched_compr));
    bufp->fullBit(oldp+380,(vlSelfRef.top_soc__DOT__uut__DOT__latched_trace));
    bufp->fullBit(oldp+381,(vlSelfRef.top_soc__DOT__uut__DOT__latched_is_lu));
    bufp->fullBit(oldp+382,(vlSelfRef.top_soc__DOT__uut__DOT__latched_is_lh));
    bufp->fullBit(oldp+383,(vlSelfRef.top_soc__DOT__uut__DOT__latched_is_lb));
    bufp->fullCData(oldp+384,(vlSelfRef.top_soc__DOT__uut__DOT__latched_rd),5);
    bufp->fullIData(oldp+385,(vlSelfRef.top_soc__DOT__uut__DOT__current_pc),32);
    bufp->fullCData(oldp+386,(vlSelfRef.top_soc__DOT__uut__DOT__pcpi_timeout_counter),4);
    bufp->fullBit(oldp+387,(vlSelfRef.top_soc__DOT__uut__DOT__pcpi_timeout));
    bufp->fullIData(oldp+388,(vlSelfRef.top_soc__DOT__uut__DOT__next_irq_pending),32);
    bufp->fullBit(oldp+389,(vlSelfRef.top_soc__DOT__uut__DOT__do_waitirq));
    bufp->fullIData(oldp+390,(vlSelfRef.top_soc__DOT__uut__DOT__alu_out),32);
    bufp->fullIData(oldp+391,(vlSelfRef.top_soc__DOT__uut__DOT__alu_out_q),32);
    bufp->fullBit(oldp+392,(vlSelfRef.top_soc__DOT__uut__DOT__alu_out_0));
    bufp->fullBit(oldp+393,(vlSelfRef.top_soc__DOT__uut__DOT__alu_out_0_q));
    bufp->fullBit(oldp+394,(vlSelfRef.top_soc__DOT__uut__DOT__alu_wait));
    bufp->fullBit(oldp+395,(vlSelfRef.top_soc__DOT__uut__DOT__alu_wait_2));
    bufp->fullIData(oldp+396,(vlSelfRef.top_soc__DOT__uut__DOT__alu_add_sub),32);
    bufp->fullIData(oldp+397,(vlSelfRef.top_soc__DOT__uut__DOT__alu_shl),32);
    bufp->fullIData(oldp+398,(vlSelfRef.top_soc__DOT__uut__DOT__alu_shr),32);
    bufp->fullBit(oldp+399,(vlSelfRef.top_soc__DOT__uut__DOT__alu_eq));
    bufp->fullBit(oldp+400,(vlSelfRef.top_soc__DOT__uut__DOT__alu_ltu));
    bufp->fullBit(oldp+401,(vlSelfRef.top_soc__DOT__uut__DOT__alu_lts));
    bufp->fullBit(oldp+402,(vlSelfRef.top_soc__DOT__uut__DOT__clear_prefetched_high_word_q));
    bufp->fullBit(oldp+403,(vlSelfRef.top_soc__DOT__uut__DOT__cpuregs_write));
    bufp->fullIData(oldp+404,(vlSelfRef.top_soc__DOT__uut__DOT__cpuregs_wrdata),32);
    bufp->fullIData(oldp+405,(vlSelfRef.top_soc__DOT__uut__DOT__cpuregs_rs1),32);
    bufp->fullIData(oldp+406,(vlSelfRef.top_soc__DOT__uut__DOT__cpuregs_rs2),32);
    bufp->fullCData(oldp+407,(vlSelfRef.top_soc__DOT__uut__DOT__decoded_rs),5);
}
