// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Symbol table implementation internals

#include "Vtop__pch.h"

Vtop__Syms::Vtop__Syms(VerilatedContext* contextp, const char* namep, Vtop* modelp)
    : VerilatedSyms{contextp}
    // Setup internal state of the Syms class
    , __Vm_modelp{modelp}
    // Setup top module instance
    , TOP{this, namep}
{
    // Check resources
    Verilated::stackCheck(470);
    // Setup sub module instances
    TOP__constants_pkg.ctor(this, "constants_pkg");
    // Configure time unit / time precision
    _vm_contextp__->timeunit(-9);
    _vm_contextp__->timeprecision(-12);
    // Setup each module's pointers to their submodules
    TOP.__PVT__constants_pkg = &TOP__constants_pkg;
    // Setup each module's pointer back to symbol table (for public functions)
    TOP.__Vconfigure(true);
    TOP__constants_pkg.__Vconfigure(true);
    // Setup scopes
    __Vscopep_TOP = new VerilatedScope{this, "TOP", "TOP", "<null>", 0, VerilatedScope::SCOPE_OTHER};
    __Vscopep_constants_pkg = new VerilatedScope{this, "constants_pkg", "constants_pkg", "constants_pkg", -9, VerilatedScope::SCOPE_PACKAGE};
    __Vscopep_top_soc = new VerilatedScope{this, "top_soc", "top_soc", "top_soc", -9, VerilatedScope::SCOPE_MODULE};
    __Vscopep_top_soc__u_bnn_accelerator = new VerilatedScope{this, "top_soc.u_bnn_accelerator", "u_bnn_accelerator", "bnn_axi_wrapper", -9, VerilatedScope::SCOPE_MODULE};
    __Vscopep_top_soc__u_bnn_accelerator__i_bnn_core = new VerilatedScope{this, "top_soc.u_bnn_accelerator.i_bnn_core", "i_bnn_core", "bnn_core", -9, VerilatedScope::SCOPE_MODULE};
    __Vscopep_top_soc__u_bnn_accelerator__i_bnn_core__pe = new VerilatedScope{this, "top_soc.u_bnn_accelerator.i_bnn_core.pe", "pe", "processing_element", -9, VerilatedScope::SCOPE_MODULE};
    __Vscopep_top_soc__uut = new VerilatedScope{this, "top_soc.uut", "uut", "picorv32", -9, VerilatedScope::SCOPE_MODULE};
    // Set up scope hierarchy
    __Vhier.add(0, __Vscopep_constants_pkg);
    __Vhier.add(0, __Vscopep_top_soc);
    __Vhier.add(__Vscopep_top_soc, __Vscopep_top_soc__u_bnn_accelerator);
    __Vhier.add(__Vscopep_top_soc, __Vscopep_top_soc__uut);
    __Vhier.add(__Vscopep_top_soc__u_bnn_accelerator, __Vscopep_top_soc__u_bnn_accelerator__i_bnn_core);
    __Vhier.add(__Vscopep_top_soc__u_bnn_accelerator__i_bnn_core, __Vscopep_top_soc__u_bnn_accelerator__i_bnn_core__pe);
    // Setup export functions - final: 0
    // Setup export functions - final: 1
    // Setup public variables
    __Vscopep_TOP->varInsert("clk", &(TOP.clk), false, VLVT_UINT8, VLVD_IN|VLVF_PUB_RW, 0, 0);
    __Vscopep_TOP->varInsert("led", &(TOP.led), false, VLVT_UINT8, VLVD_OUT|VLVF_PUB_RW, 0, 1 ,7,0);
    __Vscopep_TOP->varInsert("rst", &(TOP.rst), false, VLVT_UINT8, VLVD_IN|VLVF_PUB_RW, 0, 0);
    __Vscopep_TOP->varInsert("trap", &(TOP.trap), false, VLVT_UINT8, VLVD_OUT|VLVF_PUB_RW, 0, 0);
    __Vscopep_constants_pkg->varInsert("ACCUM_WIDTH", const_cast<void*>(static_cast<const void*>(&(TOP__constants_pkg.ACCUM_WIDTH))), true, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY|VLVF_SIGNED, 0, 1 ,31,0);
    __Vscopep_constants_pkg->varInsert("TOTAL_WORDS", const_cast<void*>(static_cast<const void*>(&(TOP__constants_pkg.TOTAL_WORDS))), true, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY|VLVF_SIGNED, 0, 1 ,31,0);
    __Vscopep_constants_pkg->varInsert("WORD_WIDTH", const_cast<void*>(static_cast<const void*>(&(TOP__constants_pkg.WORD_WIDTH))), true, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY|VLVF_SIGNED, 0, 1 ,31,0);
    __Vscopep_top_soc->varInsert("axi_arready", &(TOP.top_soc__DOT__axi_arready), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc->varInsert("axi_awready", &(TOP.top_soc__DOT__axi_awready), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc->varInsert("axi_bvalid", &(TOP.top_soc__DOT__axi_bvalid), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc->varInsert("axi_rdata", &(TOP.top_soc__DOT__axi_rdata), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_top_soc->varInsert("axi_rvalid", &(TOP.top_soc__DOT__axi_rvalid), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc->varInsert("axi_wready", &(TOP.top_soc__DOT__axi_wready), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc->varInsert("bram", &(TOP.top_soc__DOT__bram), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 1, 1 ,0,16383 ,31,0);
    __Vscopep_top_soc->varInsert("bram_addr", &(TOP.top_soc__DOT__bram_addr), false, VLVT_UINT16, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,13,0);
    __Vscopep_top_soc->varInsert("clk", &(TOP.top_soc__DOT__clk), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc->varInsert("inp_bram", &(TOP.top_soc__DOT__inp_bram), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 1, 1 ,0,16383 ,31,0);
    __Vscopep_top_soc->varInsert("inp_bram_addr", &(TOP.top_soc__DOT__inp_bram_addr), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_top_soc->varInsert("inp_bram_dout", &(TOP.top_soc__DOT__inp_bram_dout), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_top_soc->varInsert("led", &(TOP.top_soc__DOT__led), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,7,0);
    __Vscopep_top_soc->varInsert("led_reg", &(TOP.top_soc__DOT__led_reg), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,7,0);
    __Vscopep_top_soc->varInsert("mem_addr", &(TOP.top_soc__DOT__mem_addr), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_top_soc->varInsert("mem_instr", &(TOP.top_soc__DOT__mem_instr), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc->varInsert("mem_rdata", &(TOP.top_soc__DOT__mem_rdata), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_top_soc->varInsert("mem_ready", &(TOP.top_soc__DOT__mem_ready), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc->varInsert("mem_ready_reg", &(TOP.top_soc__DOT__mem_ready_reg), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc->varInsert("mem_valid", &(TOP.top_soc__DOT__mem_valid), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc->varInsert("mem_wdata", &(TOP.top_soc__DOT__mem_wdata), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_top_soc->varInsert("mem_wstrb", &(TOP.top_soc__DOT__mem_wstrb), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,3,0);
    __Vscopep_top_soc->varInsert("pcpi_insn", &(TOP.top_soc__DOT__pcpi_insn), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_top_soc->varInsert("pcpi_rd", &(TOP.top_soc__DOT__pcpi_rd), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_top_soc->varInsert("pcpi_ready", &(TOP.top_soc__DOT__pcpi_ready), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc->varInsert("pcpi_rs1", &(TOP.top_soc__DOT__pcpi_rs1), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_top_soc->varInsert("pcpi_rs2", &(TOP.top_soc__DOT__pcpi_rs2), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_top_soc->varInsert("pcpi_valid", &(TOP.top_soc__DOT__pcpi_valid), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc->varInsert("pcpi_wait", &(TOP.top_soc__DOT__pcpi_wait), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc->varInsert("pcpi_wr", &(TOP.top_soc__DOT__pcpi_wr), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc->varInsert("rst", &(TOP.top_soc__DOT__rst), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc->varInsert("select_bnn_axi", &(TOP.top_soc__DOT__select_bnn_axi), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc->varInsert("select_bram", &(TOP.top_soc__DOT__select_bram), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc->varInsert("select_inp_bram", &(TOP.top_soc__DOT__select_inp_bram), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc->varInsert("select_led", &(TOP.top_soc__DOT__select_led), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc->varInsert("select_wt_bram", &(TOP.top_soc__DOT__select_wt_bram), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc->varInsert("trap", &(TOP.top_soc__DOT__trap), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc->varInsert("wt_bram", &(TOP.top_soc__DOT__wt_bram), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 1, 1 ,0,16383 ,31,0);
    __Vscopep_top_soc->varInsert("wt_bram_addr", &(TOP.top_soc__DOT__wt_bram_addr), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_top_soc->varInsert("wt_bram_dout", &(TOP.top_soc__DOT__wt_bram_dout), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_top_soc__u_bnn_accelerator->varInsert("aclk", &(TOP.top_soc__DOT__u_bnn_accelerator__DOT__aclk), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc__u_bnn_accelerator->varInsert("addr_read", &(TOP.top_soc__DOT__u_bnn_accelerator__DOT__addr_read), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_top_soc__u_bnn_accelerator->varInsert("addr_write", &(TOP.top_soc__DOT__u_bnn_accelerator__DOT__addr_write), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_top_soc__u_bnn_accelerator->varInsert("ar_ready", &(TOP.top_soc__DOT__u_bnn_accelerator__DOT__ar_ready), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc__u_bnn_accelerator->varInsert("aresetn", &(TOP.top_soc__DOT__u_bnn_accelerator__DOT__aresetn), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc__u_bnn_accelerator->varInsert("aw_ready", &(TOP.top_soc__DOT__u_bnn_accelerator__DOT__aw_ready), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc__u_bnn_accelerator->varInsert("b_valid", &(TOP.top_soc__DOT__u_bnn_accelerator__DOT__b_valid), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc__u_bnn_accelerator->varInsert("bnn_busy", &(TOP.top_soc__DOT__u_bnn_accelerator__DOT__bnn_busy), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc__u_bnn_accelerator->varInsert("bnn_done", &(TOP.top_soc__DOT__u_bnn_accelerator__DOT__bnn_done), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc__u_bnn_accelerator->varInsert("bnn_result", &(TOP.top_soc__DOT__u_bnn_accelerator__DOT__bnn_result), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_top_soc__u_bnn_accelerator->varInsert("bnn_start", &(TOP.top_soc__DOT__u_bnn_accelerator__DOT__bnn_start), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc__u_bnn_accelerator->varInsert("ctrl_reg", &(TOP.top_soc__DOT__u_bnn_accelerator__DOT__ctrl_reg), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_top_soc__u_bnn_accelerator->varInsert("in_ptr_reg", &(TOP.top_soc__DOT__u_bnn_accelerator__DOT__in_ptr_reg), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_top_soc__u_bnn_accelerator->varInsert("inp_bram_addr", &(TOP.top_soc__DOT__u_bnn_accelerator__DOT__inp_bram_addr), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_top_soc__u_bnn_accelerator->varInsert("inp_bram_dout", &(TOP.top_soc__DOT__u_bnn_accelerator__DOT__inp_bram_dout), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_top_soc__u_bnn_accelerator->varInsert("r_valid", &(TOP.top_soc__DOT__u_bnn_accelerator__DOT__r_valid), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc__u_bnn_accelerator->varInsert("s_axi_araddr", &(TOP.top_soc__DOT__u_bnn_accelerator__DOT__s_axi_araddr), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_top_soc__u_bnn_accelerator->varInsert("s_axi_arready", &(TOP.top_soc__DOT__u_bnn_accelerator__DOT__s_axi_arready), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc__u_bnn_accelerator->varInsert("s_axi_arvalid", &(TOP.top_soc__DOT__u_bnn_accelerator__DOT__s_axi_arvalid), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc__u_bnn_accelerator->varInsert("s_axi_awaddr", &(TOP.top_soc__DOT__u_bnn_accelerator__DOT__s_axi_awaddr), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_top_soc__u_bnn_accelerator->varInsert("s_axi_awready", &(TOP.top_soc__DOT__u_bnn_accelerator__DOT__s_axi_awready), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc__u_bnn_accelerator->varInsert("s_axi_awvalid", &(TOP.top_soc__DOT__u_bnn_accelerator__DOT__s_axi_awvalid), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc__u_bnn_accelerator->varInsert("s_axi_bready", &(TOP.top_soc__DOT__u_bnn_accelerator__DOT__s_axi_bready), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc__u_bnn_accelerator->varInsert("s_axi_bresp", &(TOP.top_soc__DOT__u_bnn_accelerator__DOT__s_axi_bresp), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,1,0);
    __Vscopep_top_soc__u_bnn_accelerator->varInsert("s_axi_bvalid", &(TOP.top_soc__DOT__u_bnn_accelerator__DOT__s_axi_bvalid), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc__u_bnn_accelerator->varInsert("s_axi_rdata", &(TOP.top_soc__DOT__u_bnn_accelerator__DOT__s_axi_rdata), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_top_soc__u_bnn_accelerator->varInsert("s_axi_rready", &(TOP.top_soc__DOT__u_bnn_accelerator__DOT__s_axi_rready), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc__u_bnn_accelerator->varInsert("s_axi_rresp", &(TOP.top_soc__DOT__u_bnn_accelerator__DOT__s_axi_rresp), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,1,0);
    __Vscopep_top_soc__u_bnn_accelerator->varInsert("s_axi_rvalid", &(TOP.top_soc__DOT__u_bnn_accelerator__DOT__s_axi_rvalid), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc__u_bnn_accelerator->varInsert("s_axi_wdata", &(TOP.top_soc__DOT__u_bnn_accelerator__DOT__s_axi_wdata), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_top_soc__u_bnn_accelerator->varInsert("s_axi_wready", &(TOP.top_soc__DOT__u_bnn_accelerator__DOT__s_axi_wready), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc__u_bnn_accelerator->varInsert("s_axi_wvalid", &(TOP.top_soc__DOT__u_bnn_accelerator__DOT__s_axi_wvalid), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc__u_bnn_accelerator->varInsert("status_reg", &(TOP.top_soc__DOT__u_bnn_accelerator__DOT__status_reg), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_top_soc__u_bnn_accelerator->varInsert("w_ready", &(TOP.top_soc__DOT__u_bnn_accelerator__DOT__w_ready), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc__u_bnn_accelerator->varInsert("wt_bram_addr", &(TOP.top_soc__DOT__u_bnn_accelerator__DOT__wt_bram_addr), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_top_soc__u_bnn_accelerator->varInsert("wt_bram_dout", &(TOP.top_soc__DOT__u_bnn_accelerator__DOT__wt_bram_dout), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_top_soc__u_bnn_accelerator->varInsert("wt_ptr_reg", &(TOP.top_soc__DOT__u_bnn_accelerator__DOT__wt_ptr_reg), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_top_soc__u_bnn_accelerator__i_bnn_core->varInsert("busy", &(TOP.top_soc__DOT__u_bnn_accelerator__DOT__i_bnn_core__DOT__busy), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc__u_bnn_accelerator__i_bnn_core->varInsert("clear_accumulator", &(TOP.top_soc__DOT__u_bnn_accelerator__DOT__i_bnn_core__DOT__clear_accumulator), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc__u_bnn_accelerator__i_bnn_core->varInsert("clk", &(TOP.top_soc__DOT__u_bnn_accelerator__DOT__i_bnn_core__DOT__clk), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc__u_bnn_accelerator__i_bnn_core->varInsert("done", &(TOP.top_soc__DOT__u_bnn_accelerator__DOT__i_bnn_core__DOT__done), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc__u_bnn_accelerator__i_bnn_core->varInsert("enable", &(TOP.top_soc__DOT__u_bnn_accelerator__DOT__i_bnn_core__DOT__enable), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc__u_bnn_accelerator__i_bnn_core->varInsert("in_ptr", &(TOP.top_soc__DOT__u_bnn_accelerator__DOT__i_bnn_core__DOT__in_ptr), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_top_soc__u_bnn_accelerator__i_bnn_core->varInsert("inp_bram_addr", &(TOP.top_soc__DOT__u_bnn_accelerator__DOT__i_bnn_core__DOT__inp_bram_addr), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_top_soc__u_bnn_accelerator__i_bnn_core->varInsert("inp_bram_dout", &(TOP.top_soc__DOT__u_bnn_accelerator__DOT__i_bnn_core__DOT__inp_bram_dout), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_top_soc__u_bnn_accelerator__i_bnn_core->varInsert("inputs_reg", &(TOP.top_soc__DOT__u_bnn_accelerator__DOT__i_bnn_core__DOT__inputs_reg), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_top_soc__u_bnn_accelerator__i_bnn_core->varInsert("offset_count", &(TOP.top_soc__DOT__u_bnn_accelerator__DOT__i_bnn_core__DOT__offset_count), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_top_soc__u_bnn_accelerator__i_bnn_core->varInsert("pe_result", &(TOP.top_soc__DOT__u_bnn_accelerator__DOT__i_bnn_core__DOT__pe_result), false, VLVT_UINT16, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,8,0);
    __Vscopep_top_soc__u_bnn_accelerator__i_bnn_core->varInsert("result", &(TOP.top_soc__DOT__u_bnn_accelerator__DOT__i_bnn_core__DOT__result), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_top_soc__u_bnn_accelerator__i_bnn_core->varInsert("rstn", &(TOP.top_soc__DOT__u_bnn_accelerator__DOT__i_bnn_core__DOT__rstn), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc__u_bnn_accelerator__i_bnn_core->varInsert("start", &(TOP.top_soc__DOT__u_bnn_accelerator__DOT__i_bnn_core__DOT__start), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc__u_bnn_accelerator__i_bnn_core->varInsert("state", &(TOP.top_soc__DOT__u_bnn_accelerator__DOT__i_bnn_core__DOT__state), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,2,0);
    __Vscopep_top_soc__u_bnn_accelerator__i_bnn_core->varInsert("weights_reg", &(TOP.top_soc__DOT__u_bnn_accelerator__DOT__i_bnn_core__DOT__weights_reg), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_top_soc__u_bnn_accelerator__i_bnn_core->varInsert("word_idx", &(TOP.top_soc__DOT__u_bnn_accelerator__DOT__i_bnn_core__DOT__word_idx), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,2,0);
    __Vscopep_top_soc__u_bnn_accelerator__i_bnn_core->varInsert("wt_bram_addr", &(TOP.top_soc__DOT__u_bnn_accelerator__DOT__i_bnn_core__DOT__wt_bram_addr), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_top_soc__u_bnn_accelerator__i_bnn_core->varInsert("wt_bram_dout", &(TOP.top_soc__DOT__u_bnn_accelerator__DOT__i_bnn_core__DOT__wt_bram_dout), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_top_soc__u_bnn_accelerator__i_bnn_core->varInsert("wt_ptr", &(TOP.top_soc__DOT__u_bnn_accelerator__DOT__i_bnn_core__DOT__wt_ptr), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_top_soc__u_bnn_accelerator__i_bnn_core__pe->varInsert("accumulator", &(TOP.top_soc__DOT__u_bnn_accelerator__DOT__i_bnn_core__DOT__pe__DOT__accumulator), false, VLVT_UINT16, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,8,0);
    __Vscopep_top_soc__u_bnn_accelerator__i_bnn_core__pe->varInsert("clear_accumulator", &(TOP.top_soc__DOT__u_bnn_accelerator__DOT__i_bnn_core__DOT__pe__DOT__clear_accumulator), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc__u_bnn_accelerator__i_bnn_core__pe->varInsert("clk", &(TOP.top_soc__DOT__u_bnn_accelerator__DOT__i_bnn_core__DOT__pe__DOT__clk), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc__u_bnn_accelerator__i_bnn_core__pe->varInsert("enable", &(TOP.top_soc__DOT__u_bnn_accelerator__DOT__i_bnn_core__DOT__pe__DOT__enable), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc__u_bnn_accelerator__i_bnn_core__pe->varInsert("i", &(TOP.top_soc__DOT__u_bnn_accelerator__DOT__i_bnn_core__DOT__pe__DOT__i), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW|VLVF_SIGNED, 0, 1 ,31,0);
    __Vscopep_top_soc__u_bnn_accelerator__i_bnn_core__pe->varInsert("inp", &(TOP.top_soc__DOT__u_bnn_accelerator__DOT__i_bnn_core__DOT__pe__DOT__inp), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_top_soc__u_bnn_accelerator__i_bnn_core__pe->varInsert("input_register", &(TOP.top_soc__DOT__u_bnn_accelerator__DOT__i_bnn_core__DOT__pe__DOT__input_register), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_top_soc__u_bnn_accelerator__i_bnn_core__pe->varInsert("neuron_value", &(TOP.top_soc__DOT__u_bnn_accelerator__DOT__i_bnn_core__DOT__pe__DOT__neuron_value), false, VLVT_UINT16, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,8,0);
    __Vscopep_top_soc__u_bnn_accelerator__i_bnn_core__pe->varInsert("rstn", &(TOP.top_soc__DOT__u_bnn_accelerator__DOT__i_bnn_core__DOT__pe__DOT__rstn), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc__u_bnn_accelerator__i_bnn_core__pe->varInsert("stage1", &(TOP.top_soc__DOT__u_bnn_accelerator__DOT__i_bnn_core__DOT__pe__DOT__stage1), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 1, 1 ,0,15 ,1,0);
    __Vscopep_top_soc__u_bnn_accelerator__i_bnn_core__pe->varInsert("stage2", &(TOP.top_soc__DOT__u_bnn_accelerator__DOT__i_bnn_core__DOT__pe__DOT__stage2), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 1, 1 ,0,7 ,2,0);
    __Vscopep_top_soc__u_bnn_accelerator__i_bnn_core__pe->varInsert("stage3", &(TOP.top_soc__DOT__u_bnn_accelerator__DOT__i_bnn_core__DOT__pe__DOT__stage3), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 1, 1 ,0,3 ,3,0);
    __Vscopep_top_soc__u_bnn_accelerator__i_bnn_core__pe->varInsert("stage4", &(TOP.top_soc__DOT__u_bnn_accelerator__DOT__i_bnn_core__DOT__pe__DOT__stage4), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 1, 1 ,0,1 ,4,0);
    __Vscopep_top_soc__u_bnn_accelerator__i_bnn_core__pe->varInsert("sum_reg", &(TOP.top_soc__DOT__u_bnn_accelerator__DOT__i_bnn_core__DOT__pe__DOT__sum_reg), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,5,0);
    __Vscopep_top_soc__u_bnn_accelerator__i_bnn_core__pe->varInsert("weight_register", &(TOP.top_soc__DOT__u_bnn_accelerator__DOT__i_bnn_core__DOT__pe__DOT__weight_register), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_top_soc__u_bnn_accelerator__i_bnn_core__pe->varInsert("wt", &(TOP.top_soc__DOT__u_bnn_accelerator__DOT__i_bnn_core__DOT__pe__DOT__wt), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_top_soc__u_bnn_accelerator__i_bnn_core__pe->varInsert("xnor_result", &(TOP.top_soc__DOT__u_bnn_accelerator__DOT__i_bnn_core__DOT__pe__DOT__xnor_result), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_top_soc__uut->varInsert("BARREL_SHIFTER", const_cast<void*>(static_cast<const void*>(&(TOP.top_soc__DOT__uut__DOT__BARREL_SHIFTER))), true, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,0,0);
    __Vscopep_top_soc__uut->varInsert("CATCH_ILLINSN", const_cast<void*>(static_cast<const void*>(&(TOP.top_soc__DOT__uut__DOT__CATCH_ILLINSN))), true, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,0,0);
    __Vscopep_top_soc__uut->varInsert("CATCH_MISALIGN", const_cast<void*>(static_cast<const void*>(&(TOP.top_soc__DOT__uut__DOT__CATCH_MISALIGN))), true, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,0,0);
    __Vscopep_top_soc__uut->varInsert("COMPRESSED_ISA", const_cast<void*>(static_cast<const void*>(&(TOP.top_soc__DOT__uut__DOT__COMPRESSED_ISA))), true, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,0,0);
    __Vscopep_top_soc__uut->varInsert("ENABLE_COUNTERS", const_cast<void*>(static_cast<const void*>(&(TOP.top_soc__DOT__uut__DOT__ENABLE_COUNTERS))), true, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,0,0);
    __Vscopep_top_soc__uut->varInsert("ENABLE_COUNTERS64", const_cast<void*>(static_cast<const void*>(&(TOP.top_soc__DOT__uut__DOT__ENABLE_COUNTERS64))), true, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,0,0);
    __Vscopep_top_soc__uut->varInsert("ENABLE_DIV", const_cast<void*>(static_cast<const void*>(&(TOP.top_soc__DOT__uut__DOT__ENABLE_DIV))), true, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,0,0);
    __Vscopep_top_soc__uut->varInsert("ENABLE_FAST_MUL", const_cast<void*>(static_cast<const void*>(&(TOP.top_soc__DOT__uut__DOT__ENABLE_FAST_MUL))), true, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,0,0);
    __Vscopep_top_soc__uut->varInsert("ENABLE_IRQ", const_cast<void*>(static_cast<const void*>(&(TOP.top_soc__DOT__uut__DOT__ENABLE_IRQ))), true, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,0,0);
    __Vscopep_top_soc__uut->varInsert("ENABLE_IRQ_QREGS", const_cast<void*>(static_cast<const void*>(&(TOP.top_soc__DOT__uut__DOT__ENABLE_IRQ_QREGS))), true, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,0,0);
    __Vscopep_top_soc__uut->varInsert("ENABLE_IRQ_TIMER", const_cast<void*>(static_cast<const void*>(&(TOP.top_soc__DOT__uut__DOT__ENABLE_IRQ_TIMER))), true, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,0,0);
    __Vscopep_top_soc__uut->varInsert("ENABLE_MUL", const_cast<void*>(static_cast<const void*>(&(TOP.top_soc__DOT__uut__DOT__ENABLE_MUL))), true, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,0,0);
    __Vscopep_top_soc__uut->varInsert("ENABLE_PCPI", const_cast<void*>(static_cast<const void*>(&(TOP.top_soc__DOT__uut__DOT__ENABLE_PCPI))), true, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,0,0);
    __Vscopep_top_soc__uut->varInsert("ENABLE_REGS_16_31", const_cast<void*>(static_cast<const void*>(&(TOP.top_soc__DOT__uut__DOT__ENABLE_REGS_16_31))), true, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,0,0);
    __Vscopep_top_soc__uut->varInsert("ENABLE_REGS_DUALPORT", const_cast<void*>(static_cast<const void*>(&(TOP.top_soc__DOT__uut__DOT__ENABLE_REGS_DUALPORT))), true, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,0,0);
    __Vscopep_top_soc__uut->varInsert("ENABLE_TRACE", const_cast<void*>(static_cast<const void*>(&(TOP.top_soc__DOT__uut__DOT__ENABLE_TRACE))), true, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,0,0);
    __Vscopep_top_soc__uut->varInsert("LATCHED_IRQ", const_cast<void*>(static_cast<const void*>(&(TOP.top_soc__DOT__uut__DOT__LATCHED_IRQ))), true, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_top_soc__uut->varInsert("LATCHED_MEM_RDATA", const_cast<void*>(static_cast<const void*>(&(TOP.top_soc__DOT__uut__DOT__LATCHED_MEM_RDATA))), true, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,0,0);
    __Vscopep_top_soc__uut->varInsert("MASKED_IRQ", const_cast<void*>(static_cast<const void*>(&(TOP.top_soc__DOT__uut__DOT__MASKED_IRQ))), true, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_top_soc__uut->varInsert("PROGADDR_IRQ", const_cast<void*>(static_cast<const void*>(&(TOP.top_soc__DOT__uut__DOT__PROGADDR_IRQ))), true, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_top_soc__uut->varInsert("PROGADDR_RESET", const_cast<void*>(static_cast<const void*>(&(TOP.top_soc__DOT__uut__DOT__PROGADDR_RESET))), true, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_top_soc__uut->varInsert("REGS_INIT_ZERO", const_cast<void*>(static_cast<const void*>(&(TOP.top_soc__DOT__uut__DOT__REGS_INIT_ZERO))), true, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,0,0);
    __Vscopep_top_soc__uut->varInsert("STACKADDR", const_cast<void*>(static_cast<const void*>(&(TOP.top_soc__DOT__uut__DOT__STACKADDR))), true, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_top_soc__uut->varInsert("TRACE_ADDR", const_cast<void*>(static_cast<const void*>(&(TOP.top_soc__DOT__uut__DOT__TRACE_ADDR))), true, VLVT_UINT64, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,35,0);
    __Vscopep_top_soc__uut->varInsert("TRACE_BRANCH", const_cast<void*>(static_cast<const void*>(&(TOP.top_soc__DOT__uut__DOT__TRACE_BRANCH))), true, VLVT_UINT64, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,35,0);
    __Vscopep_top_soc__uut->varInsert("TRACE_IRQ", const_cast<void*>(static_cast<const void*>(&(TOP.top_soc__DOT__uut__DOT__TRACE_IRQ))), true, VLVT_UINT64, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,35,0);
    __Vscopep_top_soc__uut->varInsert("TWO_CYCLE_ALU", const_cast<void*>(static_cast<const void*>(&(TOP.top_soc__DOT__uut__DOT__TWO_CYCLE_ALU))), true, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,0,0);
    __Vscopep_top_soc__uut->varInsert("TWO_CYCLE_COMPARE", const_cast<void*>(static_cast<const void*>(&(TOP.top_soc__DOT__uut__DOT__TWO_CYCLE_COMPARE))), true, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,0,0);
    __Vscopep_top_soc__uut->varInsert("TWO_STAGE_SHIFT", const_cast<void*>(static_cast<const void*>(&(TOP.top_soc__DOT__uut__DOT__TWO_STAGE_SHIFT))), true, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,0,0);
    __Vscopep_top_soc__uut->varInsert("WITH_PCPI", const_cast<void*>(static_cast<const void*>(&(TOP.top_soc__DOT__uut__DOT__WITH_PCPI))), true, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,0,0);
    __Vscopep_top_soc__uut->varInsert("alu_add_sub", &(TOP.top_soc__DOT__uut__DOT__alu_add_sub), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_top_soc__uut->varInsert("alu_eq", &(TOP.top_soc__DOT__uut__DOT__alu_eq), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc__uut->varInsert("alu_lts", &(TOP.top_soc__DOT__uut__DOT__alu_lts), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc__uut->varInsert("alu_ltu", &(TOP.top_soc__DOT__uut__DOT__alu_ltu), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc__uut->varInsert("alu_out", &(TOP.top_soc__DOT__uut__DOT__alu_out), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_top_soc__uut->varInsert("alu_out_0", &(TOP.top_soc__DOT__uut__DOT__alu_out_0), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc__uut->varInsert("alu_out_0_q", &(TOP.top_soc__DOT__uut__DOT__alu_out_0_q), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc__uut->varInsert("alu_out_q", &(TOP.top_soc__DOT__uut__DOT__alu_out_q), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_top_soc__uut->varInsert("alu_shl", &(TOP.top_soc__DOT__uut__DOT__alu_shl), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_top_soc__uut->varInsert("alu_shr", &(TOP.top_soc__DOT__uut__DOT__alu_shr), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_top_soc__uut->varInsert("alu_wait", &(TOP.top_soc__DOT__uut__DOT__alu_wait), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc__uut->varInsert("alu_wait_2", &(TOP.top_soc__DOT__uut__DOT__alu_wait_2), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc__uut->varInsert("cached_ascii_instr", &(TOP.top_soc__DOT__uut__DOT__cached_ascii_instr), false, VLVT_UINT64, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,63,0);
    __Vscopep_top_soc__uut->varInsert("cached_insn_imm", &(TOP.top_soc__DOT__uut__DOT__cached_insn_imm), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_top_soc__uut->varInsert("cached_insn_opcode", &(TOP.top_soc__DOT__uut__DOT__cached_insn_opcode), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_top_soc__uut->varInsert("cached_insn_rd", &(TOP.top_soc__DOT__uut__DOT__cached_insn_rd), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,4,0);
    __Vscopep_top_soc__uut->varInsert("cached_insn_rs1", &(TOP.top_soc__DOT__uut__DOT__cached_insn_rs1), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,4,0);
    __Vscopep_top_soc__uut->varInsert("cached_insn_rs2", &(TOP.top_soc__DOT__uut__DOT__cached_insn_rs2), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,4,0);
    __Vscopep_top_soc__uut->varInsert("clear_prefetched_high_word", &(TOP.top_soc__DOT__uut__DOT__clear_prefetched_high_word), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc__uut->varInsert("clear_prefetched_high_word_q", &(TOP.top_soc__DOT__uut__DOT__clear_prefetched_high_word_q), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc__uut->varInsert("clk", &(TOP.top_soc__DOT__uut__DOT__clk), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc__uut->varInsert("compressed_instr", &(TOP.top_soc__DOT__uut__DOT__compressed_instr), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc__uut->varInsert("count_cycle", &(TOP.top_soc__DOT__uut__DOT__count_cycle), false, VLVT_UINT64, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,63,0);
    __Vscopep_top_soc__uut->varInsert("count_instr", &(TOP.top_soc__DOT__uut__DOT__count_instr), false, VLVT_UINT64, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,63,0);
    __Vscopep_top_soc__uut->varInsert("cpu_state", &(TOP.top_soc__DOT__uut__DOT__cpu_state), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,7,0);
    __Vscopep_top_soc__uut->varInsert("cpu_state_exec", const_cast<void*>(static_cast<const void*>(&(TOP.top_soc__DOT__uut__DOT__cpu_state_exec))), true, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,7,0);
    __Vscopep_top_soc__uut->varInsert("cpu_state_fetch", const_cast<void*>(static_cast<const void*>(&(TOP.top_soc__DOT__uut__DOT__cpu_state_fetch))), true, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,7,0);
    __Vscopep_top_soc__uut->varInsert("cpu_state_ld_rs1", const_cast<void*>(static_cast<const void*>(&(TOP.top_soc__DOT__uut__DOT__cpu_state_ld_rs1))), true, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,7,0);
    __Vscopep_top_soc__uut->varInsert("cpu_state_ld_rs2", const_cast<void*>(static_cast<const void*>(&(TOP.top_soc__DOT__uut__DOT__cpu_state_ld_rs2))), true, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,7,0);
    __Vscopep_top_soc__uut->varInsert("cpu_state_ldmem", const_cast<void*>(static_cast<const void*>(&(TOP.top_soc__DOT__uut__DOT__cpu_state_ldmem))), true, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,7,0);
    __Vscopep_top_soc__uut->varInsert("cpu_state_shift", const_cast<void*>(static_cast<const void*>(&(TOP.top_soc__DOT__uut__DOT__cpu_state_shift))), true, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,7,0);
    __Vscopep_top_soc__uut->varInsert("cpu_state_stmem", const_cast<void*>(static_cast<const void*>(&(TOP.top_soc__DOT__uut__DOT__cpu_state_stmem))), true, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,7,0);
    __Vscopep_top_soc__uut->varInsert("cpu_state_trap", const_cast<void*>(static_cast<const void*>(&(TOP.top_soc__DOT__uut__DOT__cpu_state_trap))), true, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,7,0);
    __Vscopep_top_soc__uut->varInsert("cpuregs", &(TOP.top_soc__DOT__uut__DOT__cpuregs), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 1, 1 ,0,31 ,31,0);
    __Vscopep_top_soc__uut->varInsert("cpuregs_rs1", &(TOP.top_soc__DOT__uut__DOT__cpuregs_rs1), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_top_soc__uut->varInsert("cpuregs_rs2", &(TOP.top_soc__DOT__uut__DOT__cpuregs_rs2), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_top_soc__uut->varInsert("cpuregs_wrdata", &(TOP.top_soc__DOT__uut__DOT__cpuregs_wrdata), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_top_soc__uut->varInsert("cpuregs_write", &(TOP.top_soc__DOT__uut__DOT__cpuregs_write), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc__uut->varInsert("current_pc", &(TOP.top_soc__DOT__uut__DOT__current_pc), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_top_soc__uut->varInsert("dbg_ascii_instr", &(TOP.top_soc__DOT__uut__DOT__dbg_ascii_instr), false, VLVT_UINT64, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,63,0);
    __Vscopep_top_soc__uut->varInsert("dbg_ascii_state", &(TOP.top_soc__DOT__uut__DOT__dbg_ascii_state), false, VLVT_WDATA, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,127,0);
    __Vscopep_top_soc__uut->varInsert("dbg_insn_addr", &(TOP.top_soc__DOT__uut__DOT__dbg_insn_addr), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_top_soc__uut->varInsert("dbg_insn_imm", &(TOP.top_soc__DOT__uut__DOT__dbg_insn_imm), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_top_soc__uut->varInsert("dbg_insn_opcode", &(TOP.top_soc__DOT__uut__DOT__dbg_insn_opcode), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_top_soc__uut->varInsert("dbg_insn_rd", &(TOP.top_soc__DOT__uut__DOT__dbg_insn_rd), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,4,0);
    __Vscopep_top_soc__uut->varInsert("dbg_insn_rs1", &(TOP.top_soc__DOT__uut__DOT__dbg_insn_rs1), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,4,0);
    __Vscopep_top_soc__uut->varInsert("dbg_insn_rs2", &(TOP.top_soc__DOT__uut__DOT__dbg_insn_rs2), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,4,0);
    __Vscopep_top_soc__uut->varInsert("dbg_mem_addr", &(TOP.top_soc__DOT__uut__DOT__dbg_mem_addr), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_top_soc__uut->varInsert("dbg_mem_instr", &(TOP.top_soc__DOT__uut__DOT__dbg_mem_instr), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc__uut->varInsert("dbg_mem_rdata", &(TOP.top_soc__DOT__uut__DOT__dbg_mem_rdata), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_top_soc__uut->varInsert("dbg_mem_ready", &(TOP.top_soc__DOT__uut__DOT__dbg_mem_ready), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc__uut->varInsert("dbg_mem_valid", &(TOP.top_soc__DOT__uut__DOT__dbg_mem_valid), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc__uut->varInsert("dbg_mem_wdata", &(TOP.top_soc__DOT__uut__DOT__dbg_mem_wdata), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_top_soc__uut->varInsert("dbg_mem_wstrb", &(TOP.top_soc__DOT__uut__DOT__dbg_mem_wstrb), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,3,0);
    __Vscopep_top_soc__uut->varInsert("dbg_next", &(TOP.top_soc__DOT__uut__DOT__dbg_next), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc__uut->varInsert("dbg_rs1val", &(TOP.top_soc__DOT__uut__DOT__dbg_rs1val), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_top_soc__uut->varInsert("dbg_rs1val_valid", &(TOP.top_soc__DOT__uut__DOT__dbg_rs1val_valid), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc__uut->varInsert("dbg_rs2val", &(TOP.top_soc__DOT__uut__DOT__dbg_rs2val), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_top_soc__uut->varInsert("dbg_rs2val_valid", &(TOP.top_soc__DOT__uut__DOT__dbg_rs2val_valid), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc__uut->varInsert("dbg_valid_insn", &(TOP.top_soc__DOT__uut__DOT__dbg_valid_insn), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc__uut->varInsert("decoded_imm", &(TOP.top_soc__DOT__uut__DOT__decoded_imm), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_top_soc__uut->varInsert("decoded_imm_j", &(TOP.top_soc__DOT__uut__DOT__decoded_imm_j), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_top_soc__uut->varInsert("decoded_rd", &(TOP.top_soc__DOT__uut__DOT__decoded_rd), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,4,0);
    __Vscopep_top_soc__uut->varInsert("decoded_rs", &(TOP.top_soc__DOT__uut__DOT__decoded_rs), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,4,0);
    __Vscopep_top_soc__uut->varInsert("decoded_rs1", &(TOP.top_soc__DOT__uut__DOT__decoded_rs1), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,4,0);
    __Vscopep_top_soc__uut->varInsert("decoded_rs2", &(TOP.top_soc__DOT__uut__DOT__decoded_rs2), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,4,0);
    __Vscopep_top_soc__uut->varInsert("decoder_pseudo_trigger", &(TOP.top_soc__DOT__uut__DOT__decoder_pseudo_trigger), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc__uut->varInsert("decoder_pseudo_trigger_q", &(TOP.top_soc__DOT__uut__DOT__decoder_pseudo_trigger_q), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc__uut->varInsert("decoder_trigger", &(TOP.top_soc__DOT__uut__DOT__decoder_trigger), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc__uut->varInsert("decoder_trigger_q", &(TOP.top_soc__DOT__uut__DOT__decoder_trigger_q), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc__uut->varInsert("do_waitirq", &(TOP.top_soc__DOT__uut__DOT__do_waitirq), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc__uut->varInsert("eoi", &(TOP.top_soc__DOT__uut__DOT__eoi), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_top_soc__uut->varInsert("i", &(TOP.top_soc__DOT__uut__DOT__i), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW|VLVF_SIGNED, 0, 1 ,31,0);
    __Vscopep_top_soc__uut->varInsert("instr_add", &(TOP.top_soc__DOT__uut__DOT__instr_add), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc__uut->varInsert("instr_addi", &(TOP.top_soc__DOT__uut__DOT__instr_addi), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc__uut->varInsert("instr_and", &(TOP.top_soc__DOT__uut__DOT__instr_and), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc__uut->varInsert("instr_andi", &(TOP.top_soc__DOT__uut__DOT__instr_andi), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc__uut->varInsert("instr_auipc", &(TOP.top_soc__DOT__uut__DOT__instr_auipc), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc__uut->varInsert("instr_beq", &(TOP.top_soc__DOT__uut__DOT__instr_beq), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc__uut->varInsert("instr_bge", &(TOP.top_soc__DOT__uut__DOT__instr_bge), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc__uut->varInsert("instr_bgeu", &(TOP.top_soc__DOT__uut__DOT__instr_bgeu), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc__uut->varInsert("instr_blt", &(TOP.top_soc__DOT__uut__DOT__instr_blt), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc__uut->varInsert("instr_bltu", &(TOP.top_soc__DOT__uut__DOT__instr_bltu), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc__uut->varInsert("instr_bne", &(TOP.top_soc__DOT__uut__DOT__instr_bne), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc__uut->varInsert("instr_ecall_ebreak", &(TOP.top_soc__DOT__uut__DOT__instr_ecall_ebreak), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc__uut->varInsert("instr_fence", &(TOP.top_soc__DOT__uut__DOT__instr_fence), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc__uut->varInsert("instr_getq", &(TOP.top_soc__DOT__uut__DOT__instr_getq), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc__uut->varInsert("instr_jal", &(TOP.top_soc__DOT__uut__DOT__instr_jal), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc__uut->varInsert("instr_jalr", &(TOP.top_soc__DOT__uut__DOT__instr_jalr), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc__uut->varInsert("instr_lb", &(TOP.top_soc__DOT__uut__DOT__instr_lb), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc__uut->varInsert("instr_lbu", &(TOP.top_soc__DOT__uut__DOT__instr_lbu), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc__uut->varInsert("instr_lh", &(TOP.top_soc__DOT__uut__DOT__instr_lh), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc__uut->varInsert("instr_lhu", &(TOP.top_soc__DOT__uut__DOT__instr_lhu), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc__uut->varInsert("instr_lui", &(TOP.top_soc__DOT__uut__DOT__instr_lui), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc__uut->varInsert("instr_lw", &(TOP.top_soc__DOT__uut__DOT__instr_lw), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc__uut->varInsert("instr_maskirq", &(TOP.top_soc__DOT__uut__DOT__instr_maskirq), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc__uut->varInsert("instr_or", &(TOP.top_soc__DOT__uut__DOT__instr_or), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc__uut->varInsert("instr_ori", &(TOP.top_soc__DOT__uut__DOT__instr_ori), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc__uut->varInsert("instr_rdcycle", &(TOP.top_soc__DOT__uut__DOT__instr_rdcycle), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc__uut->varInsert("instr_rdcycleh", &(TOP.top_soc__DOT__uut__DOT__instr_rdcycleh), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc__uut->varInsert("instr_rdinstr", &(TOP.top_soc__DOT__uut__DOT__instr_rdinstr), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc__uut->varInsert("instr_rdinstrh", &(TOP.top_soc__DOT__uut__DOT__instr_rdinstrh), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc__uut->varInsert("instr_retirq", &(TOP.top_soc__DOT__uut__DOT__instr_retirq), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc__uut->varInsert("instr_sb", &(TOP.top_soc__DOT__uut__DOT__instr_sb), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc__uut->varInsert("instr_setq", &(TOP.top_soc__DOT__uut__DOT__instr_setq), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc__uut->varInsert("instr_sh", &(TOP.top_soc__DOT__uut__DOT__instr_sh), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc__uut->varInsert("instr_sll", &(TOP.top_soc__DOT__uut__DOT__instr_sll), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc__uut->varInsert("instr_slli", &(TOP.top_soc__DOT__uut__DOT__instr_slli), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc__uut->varInsert("instr_slt", &(TOP.top_soc__DOT__uut__DOT__instr_slt), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc__uut->varInsert("instr_slti", &(TOP.top_soc__DOT__uut__DOT__instr_slti), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc__uut->varInsert("instr_sltiu", &(TOP.top_soc__DOT__uut__DOT__instr_sltiu), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc__uut->varInsert("instr_sltu", &(TOP.top_soc__DOT__uut__DOT__instr_sltu), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc__uut->varInsert("instr_sra", &(TOP.top_soc__DOT__uut__DOT__instr_sra), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc__uut->varInsert("instr_srai", &(TOP.top_soc__DOT__uut__DOT__instr_srai), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc__uut->varInsert("instr_srl", &(TOP.top_soc__DOT__uut__DOT__instr_srl), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc__uut->varInsert("instr_srli", &(TOP.top_soc__DOT__uut__DOT__instr_srli), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc__uut->varInsert("instr_sub", &(TOP.top_soc__DOT__uut__DOT__instr_sub), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc__uut->varInsert("instr_sw", &(TOP.top_soc__DOT__uut__DOT__instr_sw), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc__uut->varInsert("instr_timer", &(TOP.top_soc__DOT__uut__DOT__instr_timer), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc__uut->varInsert("instr_trap", &(TOP.top_soc__DOT__uut__DOT__instr_trap), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc__uut->varInsert("instr_waitirq", &(TOP.top_soc__DOT__uut__DOT__instr_waitirq), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc__uut->varInsert("instr_xor", &(TOP.top_soc__DOT__uut__DOT__instr_xor), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc__uut->varInsert("instr_xori", &(TOP.top_soc__DOT__uut__DOT__instr_xori), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc__uut->varInsert("irq", &(TOP.top_soc__DOT__uut__DOT__irq), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_top_soc__uut->varInsert("irq_active", &(TOP.top_soc__DOT__uut__DOT__irq_active), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc__uut->varInsert("irq_buserror", const_cast<void*>(static_cast<const void*>(&(TOP.top_soc__DOT__uut__DOT__irq_buserror))), true, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW|VLVF_SIGNED, 0, 1 ,31,0);
    __Vscopep_top_soc__uut->varInsert("irq_delay", &(TOP.top_soc__DOT__uut__DOT__irq_delay), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc__uut->varInsert("irq_ebreak", const_cast<void*>(static_cast<const void*>(&(TOP.top_soc__DOT__uut__DOT__irq_ebreak))), true, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW|VLVF_SIGNED, 0, 1 ,31,0);
    __Vscopep_top_soc__uut->varInsert("irq_mask", &(TOP.top_soc__DOT__uut__DOT__irq_mask), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_top_soc__uut->varInsert("irq_pending", &(TOP.top_soc__DOT__uut__DOT__irq_pending), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_top_soc__uut->varInsert("irq_state", &(TOP.top_soc__DOT__uut__DOT__irq_state), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,1,0);
    __Vscopep_top_soc__uut->varInsert("irq_timer", const_cast<void*>(static_cast<const void*>(&(TOP.top_soc__DOT__uut__DOT__irq_timer))), true, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW|VLVF_SIGNED, 0, 1 ,31,0);
    __Vscopep_top_soc__uut->varInsert("irqregs_offset", const_cast<void*>(static_cast<const void*>(&(TOP.top_soc__DOT__uut__DOT__irqregs_offset))), true, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW|VLVF_SIGNED, 0, 1 ,31,0);
    __Vscopep_top_soc__uut->varInsert("is_alu_reg_imm", &(TOP.top_soc__DOT__uut__DOT__is_alu_reg_imm), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc__uut->varInsert("is_alu_reg_reg", &(TOP.top_soc__DOT__uut__DOT__is_alu_reg_reg), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc__uut->varInsert("is_beq_bne_blt_bge_bltu_bgeu", &(TOP.top_soc__DOT__uut__DOT__is_beq_bne_blt_bge_bltu_bgeu), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc__uut->varInsert("is_compare", &(TOP.top_soc__DOT__uut__DOT__is_compare), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc__uut->varInsert("is_jalr_addi_slti_sltiu_xori_ori_andi", &(TOP.top_soc__DOT__uut__DOT__is_jalr_addi_slti_sltiu_xori_ori_andi), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc__uut->varInsert("is_lb_lh_lw_lbu_lhu", &(TOP.top_soc__DOT__uut__DOT__is_lb_lh_lw_lbu_lhu), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc__uut->varInsert("is_lbu_lhu_lw", &(TOP.top_soc__DOT__uut__DOT__is_lbu_lhu_lw), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc__uut->varInsert("is_lui_auipc_jal", &(TOP.top_soc__DOT__uut__DOT__is_lui_auipc_jal), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc__uut->varInsert("is_lui_auipc_jal_jalr_addi_add_sub", &(TOP.top_soc__DOT__uut__DOT__is_lui_auipc_jal_jalr_addi_add_sub), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc__uut->varInsert("is_rdcycle_rdcycleh_rdinstr_rdinstrh", &(TOP.top_soc__DOT__uut__DOT__is_rdcycle_rdcycleh_rdinstr_rdinstrh), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc__uut->varInsert("is_sb_sh_sw", &(TOP.top_soc__DOT__uut__DOT__is_sb_sh_sw), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc__uut->varInsert("is_sll_srl_sra", &(TOP.top_soc__DOT__uut__DOT__is_sll_srl_sra), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc__uut->varInsert("is_slli_srli_srai", &(TOP.top_soc__DOT__uut__DOT__is_slli_srli_srai), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc__uut->varInsert("is_slti_blt_slt", &(TOP.top_soc__DOT__uut__DOT__is_slti_blt_slt), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc__uut->varInsert("is_sltiu_bltu_sltu", &(TOP.top_soc__DOT__uut__DOT__is_sltiu_bltu_sltu), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc__uut->varInsert("last_mem_valid", &(TOP.top_soc__DOT__uut__DOT__last_mem_valid), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc__uut->varInsert("latched_branch", &(TOP.top_soc__DOT__uut__DOT__latched_branch), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc__uut->varInsert("latched_compr", &(TOP.top_soc__DOT__uut__DOT__latched_compr), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc__uut->varInsert("latched_is_lb", &(TOP.top_soc__DOT__uut__DOT__latched_is_lb), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc__uut->varInsert("latched_is_lh", &(TOP.top_soc__DOT__uut__DOT__latched_is_lh), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc__uut->varInsert("latched_is_lu", &(TOP.top_soc__DOT__uut__DOT__latched_is_lu), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc__uut->varInsert("latched_rd", &(TOP.top_soc__DOT__uut__DOT__latched_rd), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,4,0);
    __Vscopep_top_soc__uut->varInsert("latched_stalu", &(TOP.top_soc__DOT__uut__DOT__latched_stalu), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc__uut->varInsert("latched_store", &(TOP.top_soc__DOT__uut__DOT__latched_store), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc__uut->varInsert("latched_trace", &(TOP.top_soc__DOT__uut__DOT__latched_trace), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc__uut->varInsert("launch_next_insn", &(TOP.top_soc__DOT__uut__DOT__launch_next_insn), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc__uut->varInsert("mem_16bit_buffer", &(TOP.top_soc__DOT__uut__DOT__mem_16bit_buffer), false, VLVT_UINT16, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,15,0);
    __Vscopep_top_soc__uut->varInsert("mem_addr", &(TOP.top_soc__DOT__uut__DOT__mem_addr), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_top_soc__uut->varInsert("mem_busy", &(TOP.top_soc__DOT__uut__DOT__mem_busy), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc__uut->varInsert("mem_do_prefetch", &(TOP.top_soc__DOT__uut__DOT__mem_do_prefetch), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc__uut->varInsert("mem_do_rdata", &(TOP.top_soc__DOT__uut__DOT__mem_do_rdata), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc__uut->varInsert("mem_do_rinst", &(TOP.top_soc__DOT__uut__DOT__mem_do_rinst), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc__uut->varInsert("mem_do_wdata", &(TOP.top_soc__DOT__uut__DOT__mem_do_wdata), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc__uut->varInsert("mem_done", &(TOP.top_soc__DOT__uut__DOT__mem_done), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc__uut->varInsert("mem_instr", &(TOP.top_soc__DOT__uut__DOT__mem_instr), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc__uut->varInsert("mem_la_addr", &(TOP.top_soc__DOT__uut__DOT__mem_la_addr), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_top_soc__uut->varInsert("mem_la_firstword", &(TOP.top_soc__DOT__uut__DOT__mem_la_firstword), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc__uut->varInsert("mem_la_firstword_reg", &(TOP.top_soc__DOT__uut__DOT__mem_la_firstword_reg), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc__uut->varInsert("mem_la_firstword_xfer", &(TOP.top_soc__DOT__uut__DOT__mem_la_firstword_xfer), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc__uut->varInsert("mem_la_read", &(TOP.top_soc__DOT__uut__DOT__mem_la_read), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc__uut->varInsert("mem_la_secondword", &(TOP.top_soc__DOT__uut__DOT__mem_la_secondword), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc__uut->varInsert("mem_la_use_prefetched_high_word", &(TOP.top_soc__DOT__uut__DOT__mem_la_use_prefetched_high_word), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc__uut->varInsert("mem_la_wdata", &(TOP.top_soc__DOT__uut__DOT__mem_la_wdata), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_top_soc__uut->varInsert("mem_la_write", &(TOP.top_soc__DOT__uut__DOT__mem_la_write), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc__uut->varInsert("mem_la_wstrb", &(TOP.top_soc__DOT__uut__DOT__mem_la_wstrb), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,3,0);
    __Vscopep_top_soc__uut->varInsert("mem_rdata", &(TOP.top_soc__DOT__uut__DOT__mem_rdata), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_top_soc__uut->varInsert("mem_rdata_latched", &(TOP.top_soc__DOT__uut__DOT__mem_rdata_latched), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_top_soc__uut->varInsert("mem_rdata_latched_noshuffle", &(TOP.top_soc__DOT__uut__DOT__mem_rdata_latched_noshuffle), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_top_soc__uut->varInsert("mem_rdata_q", &(TOP.top_soc__DOT__uut__DOT__mem_rdata_q), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_top_soc__uut->varInsert("mem_rdata_word", &(TOP.top_soc__DOT__uut__DOT__mem_rdata_word), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_top_soc__uut->varInsert("mem_ready", &(TOP.top_soc__DOT__uut__DOT__mem_ready), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc__uut->varInsert("mem_state", &(TOP.top_soc__DOT__uut__DOT__mem_state), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,1,0);
    __Vscopep_top_soc__uut->varInsert("mem_valid", &(TOP.top_soc__DOT__uut__DOT__mem_valid), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc__uut->varInsert("mem_wdata", &(TOP.top_soc__DOT__uut__DOT__mem_wdata), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_top_soc__uut->varInsert("mem_wordsize", &(TOP.top_soc__DOT__uut__DOT__mem_wordsize), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,1,0);
    __Vscopep_top_soc__uut->varInsert("mem_wstrb", &(TOP.top_soc__DOT__uut__DOT__mem_wstrb), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,3,0);
    __Vscopep_top_soc__uut->varInsert("mem_xfer", &(TOP.top_soc__DOT__uut__DOT__mem_xfer), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc__uut->varInsert("new_ascii_instr", &(TOP.top_soc__DOT__uut__DOT__new_ascii_instr), false, VLVT_UINT64, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,63,0);
    __Vscopep_top_soc__uut->varInsert("next_insn_opcode", &(TOP.top_soc__DOT__uut__DOT__next_insn_opcode), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_top_soc__uut->varInsert("next_irq_pending", &(TOP.top_soc__DOT__uut__DOT__next_irq_pending), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_top_soc__uut->varInsert("next_pc", &(TOP.top_soc__DOT__uut__DOT__next_pc), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_top_soc__uut->varInsert("pcpi_div_rd", &(TOP.top_soc__DOT__uut__DOT__pcpi_div_rd), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_top_soc__uut->varInsert("pcpi_div_ready", &(TOP.top_soc__DOT__uut__DOT__pcpi_div_ready), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc__uut->varInsert("pcpi_div_wait", &(TOP.top_soc__DOT__uut__DOT__pcpi_div_wait), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc__uut->varInsert("pcpi_div_wr", &(TOP.top_soc__DOT__uut__DOT__pcpi_div_wr), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc__uut->varInsert("pcpi_insn", &(TOP.top_soc__DOT__uut__DOT__pcpi_insn), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_top_soc__uut->varInsert("pcpi_int_rd", &(TOP.top_soc__DOT__uut__DOT__pcpi_int_rd), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_top_soc__uut->varInsert("pcpi_int_ready", &(TOP.top_soc__DOT__uut__DOT__pcpi_int_ready), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc__uut->varInsert("pcpi_int_wait", &(TOP.top_soc__DOT__uut__DOT__pcpi_int_wait), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc__uut->varInsert("pcpi_int_wr", &(TOP.top_soc__DOT__uut__DOT__pcpi_int_wr), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc__uut->varInsert("pcpi_mul_rd", &(TOP.top_soc__DOT__uut__DOT__pcpi_mul_rd), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_top_soc__uut->varInsert("pcpi_mul_ready", &(TOP.top_soc__DOT__uut__DOT__pcpi_mul_ready), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc__uut->varInsert("pcpi_mul_wait", &(TOP.top_soc__DOT__uut__DOT__pcpi_mul_wait), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc__uut->varInsert("pcpi_mul_wr", &(TOP.top_soc__DOT__uut__DOT__pcpi_mul_wr), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc__uut->varInsert("pcpi_rd", &(TOP.top_soc__DOT__uut__DOT__pcpi_rd), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_top_soc__uut->varInsert("pcpi_ready", &(TOP.top_soc__DOT__uut__DOT__pcpi_ready), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc__uut->varInsert("pcpi_rs1", &(TOP.top_soc__DOT__uut__DOT__pcpi_rs1), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_top_soc__uut->varInsert("pcpi_rs2", &(TOP.top_soc__DOT__uut__DOT__pcpi_rs2), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_top_soc__uut->varInsert("pcpi_timeout", &(TOP.top_soc__DOT__uut__DOT__pcpi_timeout), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc__uut->varInsert("pcpi_timeout_counter", &(TOP.top_soc__DOT__uut__DOT__pcpi_timeout_counter), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,3,0);
    __Vscopep_top_soc__uut->varInsert("pcpi_valid", &(TOP.top_soc__DOT__uut__DOT__pcpi_valid), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc__uut->varInsert("pcpi_wait", &(TOP.top_soc__DOT__uut__DOT__pcpi_wait), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc__uut->varInsert("pcpi_wr", &(TOP.top_soc__DOT__uut__DOT__pcpi_wr), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc__uut->varInsert("prefetched_high_word", &(TOP.top_soc__DOT__uut__DOT__prefetched_high_word), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc__uut->varInsert("q_ascii_instr", &(TOP.top_soc__DOT__uut__DOT__q_ascii_instr), false, VLVT_UINT64, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,63,0);
    __Vscopep_top_soc__uut->varInsert("q_insn_imm", &(TOP.top_soc__DOT__uut__DOT__q_insn_imm), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_top_soc__uut->varInsert("q_insn_opcode", &(TOP.top_soc__DOT__uut__DOT__q_insn_opcode), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_top_soc__uut->varInsert("q_insn_rd", &(TOP.top_soc__DOT__uut__DOT__q_insn_rd), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,4,0);
    __Vscopep_top_soc__uut->varInsert("q_insn_rs1", &(TOP.top_soc__DOT__uut__DOT__q_insn_rs1), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,4,0);
    __Vscopep_top_soc__uut->varInsert("q_insn_rs2", &(TOP.top_soc__DOT__uut__DOT__q_insn_rs2), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,4,0);
    __Vscopep_top_soc__uut->varInsert("reg_next_pc", &(TOP.top_soc__DOT__uut__DOT__reg_next_pc), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_top_soc__uut->varInsert("reg_op1", &(TOP.top_soc__DOT__uut__DOT__reg_op1), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_top_soc__uut->varInsert("reg_op2", &(TOP.top_soc__DOT__uut__DOT__reg_op2), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_top_soc__uut->varInsert("reg_out", &(TOP.top_soc__DOT__uut__DOT__reg_out), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_top_soc__uut->varInsert("reg_pc", &(TOP.top_soc__DOT__uut__DOT__reg_pc), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_top_soc__uut->varInsert("reg_sh", &(TOP.top_soc__DOT__uut__DOT__reg_sh), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,4,0);
    __Vscopep_top_soc__uut->varInsert("regfile_size", const_cast<void*>(static_cast<const void*>(&(TOP.top_soc__DOT__uut__DOT__regfile_size))), true, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW|VLVF_SIGNED, 0, 1 ,31,0);
    __Vscopep_top_soc__uut->varInsert("regindex_bits", const_cast<void*>(static_cast<const void*>(&(TOP.top_soc__DOT__uut__DOT__regindex_bits))), true, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW|VLVF_SIGNED, 0, 1 ,31,0);
    __Vscopep_top_soc__uut->varInsert("resetn", &(TOP.top_soc__DOT__uut__DOT__resetn), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc__uut->varInsert("set_mem_do_rdata", &(TOP.top_soc__DOT__uut__DOT__set_mem_do_rdata), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc__uut->varInsert("set_mem_do_rinst", &(TOP.top_soc__DOT__uut__DOT__set_mem_do_rinst), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc__uut->varInsert("set_mem_do_wdata", &(TOP.top_soc__DOT__uut__DOT__set_mem_do_wdata), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc__uut->varInsert("timer", &(TOP.top_soc__DOT__uut__DOT__timer), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_top_soc__uut->varInsert("trace_data", &(TOP.top_soc__DOT__uut__DOT__trace_data), false, VLVT_UINT64, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,35,0);
    __Vscopep_top_soc__uut->varInsert("trace_valid", &(TOP.top_soc__DOT__uut__DOT__trace_valid), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_top_soc__uut->varInsert("trap", &(TOP.top_soc__DOT__uut__DOT__trap), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
}

Vtop__Syms::~Vtop__Syms() {
    // Tear down scope hierarchy
    __Vhier.remove(0, __Vscopep_constants_pkg);
    __Vhier.remove(0, __Vscopep_top_soc);
    __Vhier.remove(__Vscopep_top_soc, __Vscopep_top_soc__u_bnn_accelerator);
    __Vhier.remove(__Vscopep_top_soc, __Vscopep_top_soc__uut);
    __Vhier.remove(__Vscopep_top_soc__u_bnn_accelerator, __Vscopep_top_soc__u_bnn_accelerator__i_bnn_core);
    __Vhier.remove(__Vscopep_top_soc__u_bnn_accelerator__i_bnn_core, __Vscopep_top_soc__u_bnn_accelerator__i_bnn_core__pe);
    // Clear keys from hierarchy map after values have been removed
    __Vhier.clear();
    // Tear down scopes
    VL_DO_CLEAR(delete __Vscopep_TOP, __Vscopep_TOP = nullptr);
    VL_DO_CLEAR(delete __Vscopep_constants_pkg, __Vscopep_constants_pkg = nullptr);
    VL_DO_CLEAR(delete __Vscopep_top_soc, __Vscopep_top_soc = nullptr);
    VL_DO_CLEAR(delete __Vscopep_top_soc__u_bnn_accelerator, __Vscopep_top_soc__u_bnn_accelerator = nullptr);
    VL_DO_CLEAR(delete __Vscopep_top_soc__u_bnn_accelerator__i_bnn_core, __Vscopep_top_soc__u_bnn_accelerator__i_bnn_core = nullptr);
    VL_DO_CLEAR(delete __Vscopep_top_soc__u_bnn_accelerator__i_bnn_core__pe, __Vscopep_top_soc__u_bnn_accelerator__i_bnn_core__pe = nullptr);
    VL_DO_CLEAR(delete __Vscopep_top_soc__uut, __Vscopep_top_soc__uut = nullptr);
    // Tear down sub module instances
    TOP__constants_pkg.dtor();
}
