// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Symbol table implementation internals

#include "Vtop__pch.h"

Vtop__Syms::Vtop__Syms(VerilatedContext* contextp, const char* namep, Vtop* modelp)
    : VerilatedSyms{contextp}
    // Setup internal state of the Syms class
    , __Vm_modelp{modelp}
    // Setup top module instance
    , TOP{this, namep}
{
    // Check resources
    Verilated::stackCheck(358);
    // Setup sub module instances
    TOP__constants_pkg.ctor(this, "constants_pkg");
    // Configure time unit / time precision
    _vm_contextp__->timeunit(-9);
    _vm_contextp__->timeprecision(-12);
    // Setup each module's pointers to their submodules
    TOP.__PVT__constants_pkg = &TOP__constants_pkg;
    // Setup each module's pointer back to symbol table (for public functions)
    TOP.__Vconfigure(true);
    TOP__constants_pkg.__Vconfigure(true);
    // Setup scopes
    __Vscopep_TOP = new VerilatedScope{this, "TOP", "TOP", "<null>", 0, VerilatedScope::SCOPE_OTHER};
    __Vscopep_bnn_core = new VerilatedScope{this, "bnn_core", "bnn_core", "bnn_core", -9, VerilatedScope::SCOPE_MODULE};
    __Vscopep_bnn_core__pe_array__BRA__0__KET__ = new VerilatedScope{this, "bnn_core.pe_array[0]", "pe_array[0]", "<null>", -9, VerilatedScope::SCOPE_OTHER};
    __Vscopep_bnn_core__pe_array__BRA__0__KET____pe = new VerilatedScope{this, "bnn_core.pe_array[0].pe", "pe", "processing_element", -9, VerilatedScope::SCOPE_MODULE};
    __Vscopep_bnn_core__pe_array__BRA__1__KET__ = new VerilatedScope{this, "bnn_core.pe_array[1]", "pe_array[1]", "<null>", -9, VerilatedScope::SCOPE_OTHER};
    __Vscopep_bnn_core__pe_array__BRA__1__KET____pe = new VerilatedScope{this, "bnn_core.pe_array[1].pe", "pe", "processing_element", -9, VerilatedScope::SCOPE_MODULE};
    __Vscopep_bnn_core__pe_array__BRA__2__KET__ = new VerilatedScope{this, "bnn_core.pe_array[2]", "pe_array[2]", "<null>", -9, VerilatedScope::SCOPE_OTHER};
    __Vscopep_bnn_core__pe_array__BRA__2__KET____pe = new VerilatedScope{this, "bnn_core.pe_array[2].pe", "pe", "processing_element", -9, VerilatedScope::SCOPE_MODULE};
    __Vscopep_bnn_core__pe_array__BRA__3__KET__ = new VerilatedScope{this, "bnn_core.pe_array[3]", "pe_array[3]", "<null>", -9, VerilatedScope::SCOPE_OTHER};
    __Vscopep_bnn_core__pe_array__BRA__3__KET____pe = new VerilatedScope{this, "bnn_core.pe_array[3].pe", "pe", "processing_element", -9, VerilatedScope::SCOPE_MODULE};
    __Vscopep_bnn_core__pe_array__BRA__4__KET__ = new VerilatedScope{this, "bnn_core.pe_array[4]", "pe_array[4]", "<null>", -9, VerilatedScope::SCOPE_OTHER};
    __Vscopep_bnn_core__pe_array__BRA__4__KET____pe = new VerilatedScope{this, "bnn_core.pe_array[4].pe", "pe", "processing_element", -9, VerilatedScope::SCOPE_MODULE};
    __Vscopep_bnn_core__pe_array__BRA__5__KET__ = new VerilatedScope{this, "bnn_core.pe_array[5]", "pe_array[5]", "<null>", -9, VerilatedScope::SCOPE_OTHER};
    __Vscopep_bnn_core__pe_array__BRA__5__KET____pe = new VerilatedScope{this, "bnn_core.pe_array[5].pe", "pe", "processing_element", -9, VerilatedScope::SCOPE_MODULE};
    __Vscopep_bnn_core__pe_array__BRA__6__KET__ = new VerilatedScope{this, "bnn_core.pe_array[6]", "pe_array[6]", "<null>", -9, VerilatedScope::SCOPE_OTHER};
    __Vscopep_bnn_core__pe_array__BRA__6__KET____pe = new VerilatedScope{this, "bnn_core.pe_array[6].pe", "pe", "processing_element", -9, VerilatedScope::SCOPE_MODULE};
    __Vscopep_bnn_core__pe_array__BRA__7__KET__ = new VerilatedScope{this, "bnn_core.pe_array[7]", "pe_array[7]", "<null>", -9, VerilatedScope::SCOPE_OTHER};
    __Vscopep_bnn_core__pe_array__BRA__7__KET____pe = new VerilatedScope{this, "bnn_core.pe_array[7].pe", "pe", "processing_element", -9, VerilatedScope::SCOPE_MODULE};
    __Vscopep_bnn_core__unnamedblk1 = new VerilatedScope{this, "bnn_core.unnamedblk1", "unnamedblk1", "<null>", -9, VerilatedScope::SCOPE_OTHER};
    __Vscopep_bnn_core__unnamedblk2 = new VerilatedScope{this, "bnn_core.unnamedblk2", "unnamedblk2", "<null>", -9, VerilatedScope::SCOPE_OTHER};
    __Vscopep_constants_pkg = new VerilatedScope{this, "constants_pkg", "constants_pkg", "constants_pkg", -9, VerilatedScope::SCOPE_PACKAGE};
    // Set up scope hierarchy
    __Vhier.add(0, __Vscopep_bnn_core);
    __Vhier.add(0, __Vscopep_constants_pkg);
    __Vhier.add(__Vscopep_bnn_core, __Vscopep_bnn_core__pe_array__BRA__0__KET__);
    __Vhier.add(__Vscopep_bnn_core, __Vscopep_bnn_core__pe_array__BRA__1__KET__);
    __Vhier.add(__Vscopep_bnn_core, __Vscopep_bnn_core__pe_array__BRA__2__KET__);
    __Vhier.add(__Vscopep_bnn_core, __Vscopep_bnn_core__pe_array__BRA__3__KET__);
    __Vhier.add(__Vscopep_bnn_core, __Vscopep_bnn_core__pe_array__BRA__4__KET__);
    __Vhier.add(__Vscopep_bnn_core, __Vscopep_bnn_core__pe_array__BRA__5__KET__);
    __Vhier.add(__Vscopep_bnn_core, __Vscopep_bnn_core__pe_array__BRA__6__KET__);
    __Vhier.add(__Vscopep_bnn_core, __Vscopep_bnn_core__pe_array__BRA__7__KET__);
    __Vhier.add(__Vscopep_bnn_core, __Vscopep_bnn_core__unnamedblk1);
    __Vhier.add(__Vscopep_bnn_core, __Vscopep_bnn_core__unnamedblk2);
    __Vhier.add(__Vscopep_bnn_core__pe_array__BRA__0__KET__, __Vscopep_bnn_core__pe_array__BRA__0__KET____pe);
    __Vhier.add(__Vscopep_bnn_core__pe_array__BRA__1__KET__, __Vscopep_bnn_core__pe_array__BRA__1__KET____pe);
    __Vhier.add(__Vscopep_bnn_core__pe_array__BRA__2__KET__, __Vscopep_bnn_core__pe_array__BRA__2__KET____pe);
    __Vhier.add(__Vscopep_bnn_core__pe_array__BRA__3__KET__, __Vscopep_bnn_core__pe_array__BRA__3__KET____pe);
    __Vhier.add(__Vscopep_bnn_core__pe_array__BRA__4__KET__, __Vscopep_bnn_core__pe_array__BRA__4__KET____pe);
    __Vhier.add(__Vscopep_bnn_core__pe_array__BRA__5__KET__, __Vscopep_bnn_core__pe_array__BRA__5__KET____pe);
    __Vhier.add(__Vscopep_bnn_core__pe_array__BRA__6__KET__, __Vscopep_bnn_core__pe_array__BRA__6__KET____pe);
    __Vhier.add(__Vscopep_bnn_core__pe_array__BRA__7__KET__, __Vscopep_bnn_core__pe_array__BRA__7__KET____pe);
    // Setup export functions - final: 0
    // Setup export functions - final: 1
    // Setup public variables
    __Vscopep_TOP->varInsert("busy", &(TOP.busy), false, VLVT_UINT8, VLVD_OUT|VLVF_PUB_RW, 0, 0);
    __Vscopep_TOP->varInsert("clk", &(TOP.clk), false, VLVT_UINT8, VLVD_IN|VLVF_PUB_RW, 0, 0);
    __Vscopep_TOP->varInsert("done", &(TOP.done), false, VLVT_UINT8, VLVD_OUT|VLVF_PUB_RW, 0, 0);
    __Vscopep_TOP->varInsert("in_ptr", &(TOP.in_ptr), false, VLVT_UINT32, VLVD_IN|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_TOP->varInsert("inp_bram_addr", &(TOP.inp_bram_addr), false, VLVT_UINT32, VLVD_OUT|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_TOP->varInsert("inp_bram_dout", &(TOP.inp_bram_dout), false, VLVT_UINT32, VLVD_IN|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_TOP->varInsert("result", &(TOP.result), false, VLVT_UINT32, VLVD_OUT|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_TOP->varInsert("rstn", &(TOP.rstn), false, VLVT_UINT8, VLVD_IN|VLVF_PUB_RW, 0, 0);
    __Vscopep_TOP->varInsert("start", &(TOP.start), false, VLVT_UINT8, VLVD_IN|VLVF_PUB_RW, 0, 0);
    __Vscopep_TOP->varInsert("thr_ptr", &(TOP.thr_ptr), false, VLVT_UINT32, VLVD_IN|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_TOP->varInsert("wt_bram_addr", &(TOP.wt_bram_addr), false, VLVT_UINT32, VLVD_OUT|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_TOP->varInsert("wt_bram_dout", &(TOP.wt_bram_dout), false, VLVT_UINT32, VLVD_IN|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_TOP->varInsert("wt_ptr", &(TOP.wt_ptr), false, VLVT_UINT32, VLVD_IN|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_bnn_core->varInsert("activ_word_idx", &(TOP.bnn_core__DOT__activ_word_idx), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,2,0);
    __Vscopep_bnn_core->varInsert("activation_buffer", &(TOP.bnn_core__DOT__activation_buffer), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 1, 1 ,0,7 ,31,0);
    __Vscopep_bnn_core->varInsert("bram_primed", &(TOP.bnn_core__DOT__bram_primed), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_bnn_core->varInsert("busy", &(TOP.bnn_core__DOT__busy), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_bnn_core->varInsert("clear_accumulator", &(TOP.bnn_core__DOT__clear_accumulator), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_bnn_core->varInsert("clk", &(TOP.bnn_core__DOT__clk), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_bnn_core->varInsert("current_desc", &(TOP.bnn_core__DOT__current_desc), false, VLVT_WDATA, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,127,0);
    __Vscopep_bnn_core->varInsert("done", &(TOP.bnn_core__DOT__done), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_bnn_core->varInsert("enable", &(TOP.bnn_core__DOT__enable), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_bnn_core->varInsert("in_ptr", &(TOP.bnn_core__DOT__in_ptr), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_bnn_core->varInsert("in_ptr_reg", &(TOP.bnn_core__DOT__in_ptr_reg), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_bnn_core->varInsert("inp_bram_addr", &(TOP.bnn_core__DOT__inp_bram_addr), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_bnn_core->varInsert("inp_bram_dout", &(TOP.bnn_core__DOT__inp_bram_dout), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_bnn_core->varInsert("input_word_last", &(TOP.bnn_core__DOT__input_word_last), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,2,0);
    __Vscopep_bnn_core->varInsert("input_words", &(TOP.bnn_core__DOT__input_words), false, VLVT_UINT16, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,15,0);
    __Vscopep_bnn_core->varInsert("layer_idx", &(TOP.bnn_core__DOT__layer_idx), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,2,0);
    __Vscopep_bnn_core->varInsert("layer_table", &(TOP.bnn_core__DOT__layer_table), false, VLVT_WDATA, VLVD_NODIR|VLVF_PUB_RW, 1, 1 ,0,7 ,127,0);
    __Vscopep_bnn_core->varInsert("neuron_idx", &(TOP.bnn_core__DOT__neuron_idx), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,2,0);
    __Vscopep_bnn_core->varInsert("output_buffer", &(TOP.bnn_core__DOT__output_buffer), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 1, 1 ,0,7 ,31,0);
    __Vscopep_bnn_core->varInsert("output_neuron_last", &(TOP.bnn_core__DOT__output_neuron_last), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,2,0);
    __Vscopep_bnn_core->varInsert("output_neurons", &(TOP.bnn_core__DOT__output_neurons), false, VLVT_UINT16, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,15,0);
    __Vscopep_bnn_core->varInsert("pe_idx", &(TOP.bnn_core__DOT__pe_idx), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,2,0);
    __Vscopep_bnn_core->varInsert("pe_result", &(TOP.bnn_core__DOT__pe_result), false, VLVT_UINT16, VLVD_NODIR|VLVF_PUB_RW|VLVF_SIGNED, 1, 1 ,0,7 ,9,0);
    __Vscopep_bnn_core->varInsert("result", &(TOP.bnn_core__DOT__result), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_bnn_core->varInsert("rstn", &(TOP.bnn_core__DOT__rstn), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_bnn_core->varInsert("start", &(TOP.bnn_core__DOT__start), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_bnn_core->varInsert("state", &(TOP.bnn_core__DOT__state), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,3,0);
    __Vscopep_bnn_core->varInsert("thr_ptr", &(TOP.bnn_core__DOT__thr_ptr), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_bnn_core->varInsert("thr_ptr_reg", &(TOP.bnn_core__DOT__thr_ptr_reg), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_bnn_core->varInsert("threshold_buffer", &(TOP.bnn_core__DOT__threshold_buffer), false, VLVT_UINT16, VLVD_NODIR|VLVF_PUB_RW, 1, 1 ,0,7 ,9,0);
    __Vscopep_bnn_core->varInsert("weights_buffer", &(TOP.bnn_core__DOT__weights_buffer), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 2, 1 ,0,7 ,0,7 ,31,0);
    __Vscopep_bnn_core->varInsert("word_idx", &(TOP.bnn_core__DOT__word_idx), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,2,0);
    __Vscopep_bnn_core->varInsert("wt_bram_addr", &(TOP.bnn_core__DOT__wt_bram_addr), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_bnn_core->varInsert("wt_bram_dout", &(TOP.bnn_core__DOT__wt_bram_dout), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_bnn_core->varInsert("wt_ptr", &(TOP.bnn_core__DOT__wt_ptr), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_bnn_core->varInsert("wt_ptr_reg", &(TOP.bnn_core__DOT__wt_ptr_reg), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_bnn_core->varInsert("wt_word_idx", &(TOP.bnn_core__DOT__wt_word_idx), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,2,0);
    __Vscopep_bnn_core__pe_array__BRA__0__KET____pe->varInsert("accumulator", &(TOP.bnn_core__DOT__pe_array__BRA__0__KET____DOT__pe__DOT__accumulator), false, VLVT_UINT16, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,9,0);
    __Vscopep_bnn_core__pe_array__BRA__0__KET____pe->varInsert("activations_buffer", &(TOP.bnn_core__DOT__pe_array__BRA__0__KET____DOT__pe__DOT__activations_buffer), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_bnn_core__pe_array__BRA__0__KET____pe->varInsert("clear_accumulator", &(TOP.bnn_core__DOT__pe_array__BRA__0__KET____DOT__pe__DOT__clear_accumulator), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_bnn_core__pe_array__BRA__0__KET____pe->varInsert("clk", &(TOP.bnn_core__DOT__pe_array__BRA__0__KET____DOT__pe__DOT__clk), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_bnn_core__pe_array__BRA__0__KET____pe->varInsert("enable", &(TOP.bnn_core__DOT__pe_array__BRA__0__KET____DOT__pe__DOT__enable), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_bnn_core__pe_array__BRA__0__KET____pe->varInsert("i", &(TOP.bnn_core__DOT__pe_array__BRA__0__KET____DOT__pe__DOT__i), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW|VLVF_SIGNED, 0, 1 ,31,0);
    __Vscopep_bnn_core__pe_array__BRA__0__KET____pe->varInsert("inp", &(TOP.bnn_core__DOT__pe_array__BRA__0__KET____DOT__pe__DOT__inp), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_bnn_core__pe_array__BRA__0__KET____pe->varInsert("neuron_value", &(TOP.bnn_core__DOT__pe_array__BRA__0__KET____DOT__pe__DOT__neuron_value), false, VLVT_UINT16, VLVD_NODIR|VLVF_PUB_RW|VLVF_SIGNED, 0, 1 ,9,0);
    __Vscopep_bnn_core__pe_array__BRA__0__KET____pe->varInsert("rstn", &(TOP.bnn_core__DOT__pe_array__BRA__0__KET____DOT__pe__DOT__rstn), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_bnn_core__pe_array__BRA__0__KET____pe->varInsert("stage1", &(TOP.bnn_core__DOT__pe_array__BRA__0__KET____DOT__pe__DOT__stage1), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 1, 1 ,0,15 ,1,0);
    __Vscopep_bnn_core__pe_array__BRA__0__KET____pe->varInsert("stage2", &(TOP.bnn_core__DOT__pe_array__BRA__0__KET____DOT__pe__DOT__stage2), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 1, 1 ,0,7 ,2,0);
    __Vscopep_bnn_core__pe_array__BRA__0__KET____pe->varInsert("stage3", &(TOP.bnn_core__DOT__pe_array__BRA__0__KET____DOT__pe__DOT__stage3), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 1, 1 ,0,3 ,3,0);
    __Vscopep_bnn_core__pe_array__BRA__0__KET____pe->varInsert("stage4", &(TOP.bnn_core__DOT__pe_array__BRA__0__KET____DOT__pe__DOT__stage4), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 1, 1 ,0,1 ,4,0);
    __Vscopep_bnn_core__pe_array__BRA__0__KET____pe->varInsert("sum_reg", &(TOP.bnn_core__DOT__pe_array__BRA__0__KET____DOT__pe__DOT__sum_reg), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,5,0);
    __Vscopep_bnn_core__pe_array__BRA__0__KET____pe->varInsert("threshold", &(TOP.bnn_core__DOT__pe_array__BRA__0__KET____DOT__pe__DOT__threshold), false, VLVT_UINT16, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,9,0);
    __Vscopep_bnn_core__pe_array__BRA__0__KET____pe->varInsert("weight_buffer", &(TOP.bnn_core__DOT__pe_array__BRA__0__KET____DOT__pe__DOT__weight_buffer), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_bnn_core__pe_array__BRA__0__KET____pe->varInsert("wt", &(TOP.bnn_core__DOT__pe_array__BRA__0__KET____DOT__pe__DOT__wt), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_bnn_core__pe_array__BRA__0__KET____pe->varInsert("xnor_result", &(TOP.bnn_core__DOT__pe_array__BRA__0__KET____DOT__pe__DOT__xnor_result), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_bnn_core__pe_array__BRA__1__KET____pe->varInsert("accumulator", &(TOP.bnn_core__DOT__pe_array__BRA__1__KET____DOT__pe__DOT__accumulator), false, VLVT_UINT16, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,9,0);
    __Vscopep_bnn_core__pe_array__BRA__1__KET____pe->varInsert("activations_buffer", &(TOP.bnn_core__DOT__pe_array__BRA__1__KET____DOT__pe__DOT__activations_buffer), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_bnn_core__pe_array__BRA__1__KET____pe->varInsert("clear_accumulator", &(TOP.bnn_core__DOT__pe_array__BRA__1__KET____DOT__pe__DOT__clear_accumulator), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_bnn_core__pe_array__BRA__1__KET____pe->varInsert("clk", &(TOP.bnn_core__DOT__pe_array__BRA__1__KET____DOT__pe__DOT__clk), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_bnn_core__pe_array__BRA__1__KET____pe->varInsert("enable", &(TOP.bnn_core__DOT__pe_array__BRA__1__KET____DOT__pe__DOT__enable), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_bnn_core__pe_array__BRA__1__KET____pe->varInsert("i", &(TOP.bnn_core__DOT__pe_array__BRA__1__KET____DOT__pe__DOT__i), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW|VLVF_SIGNED, 0, 1 ,31,0);
    __Vscopep_bnn_core__pe_array__BRA__1__KET____pe->varInsert("inp", &(TOP.bnn_core__DOT__pe_array__BRA__1__KET____DOT__pe__DOT__inp), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_bnn_core__pe_array__BRA__1__KET____pe->varInsert("neuron_value", &(TOP.bnn_core__DOT__pe_array__BRA__1__KET____DOT__pe__DOT__neuron_value), false, VLVT_UINT16, VLVD_NODIR|VLVF_PUB_RW|VLVF_SIGNED, 0, 1 ,9,0);
    __Vscopep_bnn_core__pe_array__BRA__1__KET____pe->varInsert("rstn", &(TOP.bnn_core__DOT__pe_array__BRA__1__KET____DOT__pe__DOT__rstn), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_bnn_core__pe_array__BRA__1__KET____pe->varInsert("stage1", &(TOP.bnn_core__DOT__pe_array__BRA__1__KET____DOT__pe__DOT__stage1), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 1, 1 ,0,15 ,1,0);
    __Vscopep_bnn_core__pe_array__BRA__1__KET____pe->varInsert("stage2", &(TOP.bnn_core__DOT__pe_array__BRA__1__KET____DOT__pe__DOT__stage2), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 1, 1 ,0,7 ,2,0);
    __Vscopep_bnn_core__pe_array__BRA__1__KET____pe->varInsert("stage3", &(TOP.bnn_core__DOT__pe_array__BRA__1__KET____DOT__pe__DOT__stage3), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 1, 1 ,0,3 ,3,0);
    __Vscopep_bnn_core__pe_array__BRA__1__KET____pe->varInsert("stage4", &(TOP.bnn_core__DOT__pe_array__BRA__1__KET____DOT__pe__DOT__stage4), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 1, 1 ,0,1 ,4,0);
    __Vscopep_bnn_core__pe_array__BRA__1__KET____pe->varInsert("sum_reg", &(TOP.bnn_core__DOT__pe_array__BRA__1__KET____DOT__pe__DOT__sum_reg), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,5,0);
    __Vscopep_bnn_core__pe_array__BRA__1__KET____pe->varInsert("threshold", &(TOP.bnn_core__DOT__pe_array__BRA__1__KET____DOT__pe__DOT__threshold), false, VLVT_UINT16, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,9,0);
    __Vscopep_bnn_core__pe_array__BRA__1__KET____pe->varInsert("weight_buffer", &(TOP.bnn_core__DOT__pe_array__BRA__1__KET____DOT__pe__DOT__weight_buffer), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_bnn_core__pe_array__BRA__1__KET____pe->varInsert("wt", &(TOP.bnn_core__DOT__pe_array__BRA__1__KET____DOT__pe__DOT__wt), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_bnn_core__pe_array__BRA__1__KET____pe->varInsert("xnor_result", &(TOP.bnn_core__DOT__pe_array__BRA__1__KET____DOT__pe__DOT__xnor_result), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_bnn_core__pe_array__BRA__2__KET____pe->varInsert("accumulator", &(TOP.bnn_core__DOT__pe_array__BRA__2__KET____DOT__pe__DOT__accumulator), false, VLVT_UINT16, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,9,0);
    __Vscopep_bnn_core__pe_array__BRA__2__KET____pe->varInsert("activations_buffer", &(TOP.bnn_core__DOT__pe_array__BRA__2__KET____DOT__pe__DOT__activations_buffer), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_bnn_core__pe_array__BRA__2__KET____pe->varInsert("clear_accumulator", &(TOP.bnn_core__DOT__pe_array__BRA__2__KET____DOT__pe__DOT__clear_accumulator), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_bnn_core__pe_array__BRA__2__KET____pe->varInsert("clk", &(TOP.bnn_core__DOT__pe_array__BRA__2__KET____DOT__pe__DOT__clk), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_bnn_core__pe_array__BRA__2__KET____pe->varInsert("enable", &(TOP.bnn_core__DOT__pe_array__BRA__2__KET____DOT__pe__DOT__enable), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_bnn_core__pe_array__BRA__2__KET____pe->varInsert("i", &(TOP.bnn_core__DOT__pe_array__BRA__2__KET____DOT__pe__DOT__i), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW|VLVF_SIGNED, 0, 1 ,31,0);
    __Vscopep_bnn_core__pe_array__BRA__2__KET____pe->varInsert("inp", &(TOP.bnn_core__DOT__pe_array__BRA__2__KET____DOT__pe__DOT__inp), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_bnn_core__pe_array__BRA__2__KET____pe->varInsert("neuron_value", &(TOP.bnn_core__DOT__pe_array__BRA__2__KET____DOT__pe__DOT__neuron_value), false, VLVT_UINT16, VLVD_NODIR|VLVF_PUB_RW|VLVF_SIGNED, 0, 1 ,9,0);
    __Vscopep_bnn_core__pe_array__BRA__2__KET____pe->varInsert("rstn", &(TOP.bnn_core__DOT__pe_array__BRA__2__KET____DOT__pe__DOT__rstn), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_bnn_core__pe_array__BRA__2__KET____pe->varInsert("stage1", &(TOP.bnn_core__DOT__pe_array__BRA__2__KET____DOT__pe__DOT__stage1), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 1, 1 ,0,15 ,1,0);
    __Vscopep_bnn_core__pe_array__BRA__2__KET____pe->varInsert("stage2", &(TOP.bnn_core__DOT__pe_array__BRA__2__KET____DOT__pe__DOT__stage2), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 1, 1 ,0,7 ,2,0);
    __Vscopep_bnn_core__pe_array__BRA__2__KET____pe->varInsert("stage3", &(TOP.bnn_core__DOT__pe_array__BRA__2__KET____DOT__pe__DOT__stage3), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 1, 1 ,0,3 ,3,0);
    __Vscopep_bnn_core__pe_array__BRA__2__KET____pe->varInsert("stage4", &(TOP.bnn_core__DOT__pe_array__BRA__2__KET____DOT__pe__DOT__stage4), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 1, 1 ,0,1 ,4,0);
    __Vscopep_bnn_core__pe_array__BRA__2__KET____pe->varInsert("sum_reg", &(TOP.bnn_core__DOT__pe_array__BRA__2__KET____DOT__pe__DOT__sum_reg), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,5,0);
    __Vscopep_bnn_core__pe_array__BRA__2__KET____pe->varInsert("threshold", &(TOP.bnn_core__DOT__pe_array__BRA__2__KET____DOT__pe__DOT__threshold), false, VLVT_UINT16, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,9,0);
    __Vscopep_bnn_core__pe_array__BRA__2__KET____pe->varInsert("weight_buffer", &(TOP.bnn_core__DOT__pe_array__BRA__2__KET____DOT__pe__DOT__weight_buffer), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_bnn_core__pe_array__BRA__2__KET____pe->varInsert("wt", &(TOP.bnn_core__DOT__pe_array__BRA__2__KET____DOT__pe__DOT__wt), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_bnn_core__pe_array__BRA__2__KET____pe->varInsert("xnor_result", &(TOP.bnn_core__DOT__pe_array__BRA__2__KET____DOT__pe__DOT__xnor_result), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_bnn_core__pe_array__BRA__3__KET____pe->varInsert("accumulator", &(TOP.bnn_core__DOT__pe_array__BRA__3__KET____DOT__pe__DOT__accumulator), false, VLVT_UINT16, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,9,0);
    __Vscopep_bnn_core__pe_array__BRA__3__KET____pe->varInsert("activations_buffer", &(TOP.bnn_core__DOT__pe_array__BRA__3__KET____DOT__pe__DOT__activations_buffer), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_bnn_core__pe_array__BRA__3__KET____pe->varInsert("clear_accumulator", &(TOP.bnn_core__DOT__pe_array__BRA__3__KET____DOT__pe__DOT__clear_accumulator), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_bnn_core__pe_array__BRA__3__KET____pe->varInsert("clk", &(TOP.bnn_core__DOT__pe_array__BRA__3__KET____DOT__pe__DOT__clk), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_bnn_core__pe_array__BRA__3__KET____pe->varInsert("enable", &(TOP.bnn_core__DOT__pe_array__BRA__3__KET____DOT__pe__DOT__enable), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_bnn_core__pe_array__BRA__3__KET____pe->varInsert("i", &(TOP.bnn_core__DOT__pe_array__BRA__3__KET____DOT__pe__DOT__i), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW|VLVF_SIGNED, 0, 1 ,31,0);
    __Vscopep_bnn_core__pe_array__BRA__3__KET____pe->varInsert("inp", &(TOP.bnn_core__DOT__pe_array__BRA__3__KET____DOT__pe__DOT__inp), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_bnn_core__pe_array__BRA__3__KET____pe->varInsert("neuron_value", &(TOP.bnn_core__DOT__pe_array__BRA__3__KET____DOT__pe__DOT__neuron_value), false, VLVT_UINT16, VLVD_NODIR|VLVF_PUB_RW|VLVF_SIGNED, 0, 1 ,9,0);
    __Vscopep_bnn_core__pe_array__BRA__3__KET____pe->varInsert("rstn", &(TOP.bnn_core__DOT__pe_array__BRA__3__KET____DOT__pe__DOT__rstn), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_bnn_core__pe_array__BRA__3__KET____pe->varInsert("stage1", &(TOP.bnn_core__DOT__pe_array__BRA__3__KET____DOT__pe__DOT__stage1), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 1, 1 ,0,15 ,1,0);
    __Vscopep_bnn_core__pe_array__BRA__3__KET____pe->varInsert("stage2", &(TOP.bnn_core__DOT__pe_array__BRA__3__KET____DOT__pe__DOT__stage2), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 1, 1 ,0,7 ,2,0);
    __Vscopep_bnn_core__pe_array__BRA__3__KET____pe->varInsert("stage3", &(TOP.bnn_core__DOT__pe_array__BRA__3__KET____DOT__pe__DOT__stage3), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 1, 1 ,0,3 ,3,0);
    __Vscopep_bnn_core__pe_array__BRA__3__KET____pe->varInsert("stage4", &(TOP.bnn_core__DOT__pe_array__BRA__3__KET____DOT__pe__DOT__stage4), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 1, 1 ,0,1 ,4,0);
    __Vscopep_bnn_core__pe_array__BRA__3__KET____pe->varInsert("sum_reg", &(TOP.bnn_core__DOT__pe_array__BRA__3__KET____DOT__pe__DOT__sum_reg), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,5,0);
    __Vscopep_bnn_core__pe_array__BRA__3__KET____pe->varInsert("threshold", &(TOP.bnn_core__DOT__pe_array__BRA__3__KET____DOT__pe__DOT__threshold), false, VLVT_UINT16, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,9,0);
    __Vscopep_bnn_core__pe_array__BRA__3__KET____pe->varInsert("weight_buffer", &(TOP.bnn_core__DOT__pe_array__BRA__3__KET____DOT__pe__DOT__weight_buffer), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_bnn_core__pe_array__BRA__3__KET____pe->varInsert("wt", &(TOP.bnn_core__DOT__pe_array__BRA__3__KET____DOT__pe__DOT__wt), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_bnn_core__pe_array__BRA__3__KET____pe->varInsert("xnor_result", &(TOP.bnn_core__DOT__pe_array__BRA__3__KET____DOT__pe__DOT__xnor_result), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_bnn_core__pe_array__BRA__4__KET____pe->varInsert("accumulator", &(TOP.bnn_core__DOT__pe_array__BRA__4__KET____DOT__pe__DOT__accumulator), false, VLVT_UINT16, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,9,0);
    __Vscopep_bnn_core__pe_array__BRA__4__KET____pe->varInsert("activations_buffer", &(TOP.bnn_core__DOT__pe_array__BRA__4__KET____DOT__pe__DOT__activations_buffer), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_bnn_core__pe_array__BRA__4__KET____pe->varInsert("clear_accumulator", &(TOP.bnn_core__DOT__pe_array__BRA__4__KET____DOT__pe__DOT__clear_accumulator), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_bnn_core__pe_array__BRA__4__KET____pe->varInsert("clk", &(TOP.bnn_core__DOT__pe_array__BRA__4__KET____DOT__pe__DOT__clk), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_bnn_core__pe_array__BRA__4__KET____pe->varInsert("enable", &(TOP.bnn_core__DOT__pe_array__BRA__4__KET____DOT__pe__DOT__enable), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_bnn_core__pe_array__BRA__4__KET____pe->varInsert("i", &(TOP.bnn_core__DOT__pe_array__BRA__4__KET____DOT__pe__DOT__i), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW|VLVF_SIGNED, 0, 1 ,31,0);
    __Vscopep_bnn_core__pe_array__BRA__4__KET____pe->varInsert("inp", &(TOP.bnn_core__DOT__pe_array__BRA__4__KET____DOT__pe__DOT__inp), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_bnn_core__pe_array__BRA__4__KET____pe->varInsert("neuron_value", &(TOP.bnn_core__DOT__pe_array__BRA__4__KET____DOT__pe__DOT__neuron_value), false, VLVT_UINT16, VLVD_NODIR|VLVF_PUB_RW|VLVF_SIGNED, 0, 1 ,9,0);
    __Vscopep_bnn_core__pe_array__BRA__4__KET____pe->varInsert("rstn", &(TOP.bnn_core__DOT__pe_array__BRA__4__KET____DOT__pe__DOT__rstn), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_bnn_core__pe_array__BRA__4__KET____pe->varInsert("stage1", &(TOP.bnn_core__DOT__pe_array__BRA__4__KET____DOT__pe__DOT__stage1), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 1, 1 ,0,15 ,1,0);
    __Vscopep_bnn_core__pe_array__BRA__4__KET____pe->varInsert("stage2", &(TOP.bnn_core__DOT__pe_array__BRA__4__KET____DOT__pe__DOT__stage2), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 1, 1 ,0,7 ,2,0);
    __Vscopep_bnn_core__pe_array__BRA__4__KET____pe->varInsert("stage3", &(TOP.bnn_core__DOT__pe_array__BRA__4__KET____DOT__pe__DOT__stage3), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 1, 1 ,0,3 ,3,0);
    __Vscopep_bnn_core__pe_array__BRA__4__KET____pe->varInsert("stage4", &(TOP.bnn_core__DOT__pe_array__BRA__4__KET____DOT__pe__DOT__stage4), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 1, 1 ,0,1 ,4,0);
    __Vscopep_bnn_core__pe_array__BRA__4__KET____pe->varInsert("sum_reg", &(TOP.bnn_core__DOT__pe_array__BRA__4__KET____DOT__pe__DOT__sum_reg), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,5,0);
    __Vscopep_bnn_core__pe_array__BRA__4__KET____pe->varInsert("threshold", &(TOP.bnn_core__DOT__pe_array__BRA__4__KET____DOT__pe__DOT__threshold), false, VLVT_UINT16, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,9,0);
    __Vscopep_bnn_core__pe_array__BRA__4__KET____pe->varInsert("weight_buffer", &(TOP.bnn_core__DOT__pe_array__BRA__4__KET____DOT__pe__DOT__weight_buffer), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_bnn_core__pe_array__BRA__4__KET____pe->varInsert("wt", &(TOP.bnn_core__DOT__pe_array__BRA__4__KET____DOT__pe__DOT__wt), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_bnn_core__pe_array__BRA__4__KET____pe->varInsert("xnor_result", &(TOP.bnn_core__DOT__pe_array__BRA__4__KET____DOT__pe__DOT__xnor_result), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_bnn_core__pe_array__BRA__5__KET____pe->varInsert("accumulator", &(TOP.bnn_core__DOT__pe_array__BRA__5__KET____DOT__pe__DOT__accumulator), false, VLVT_UINT16, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,9,0);
    __Vscopep_bnn_core__pe_array__BRA__5__KET____pe->varInsert("activations_buffer", &(TOP.bnn_core__DOT__pe_array__BRA__5__KET____DOT__pe__DOT__activations_buffer), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_bnn_core__pe_array__BRA__5__KET____pe->varInsert("clear_accumulator", &(TOP.bnn_core__DOT__pe_array__BRA__5__KET____DOT__pe__DOT__clear_accumulator), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_bnn_core__pe_array__BRA__5__KET____pe->varInsert("clk", &(TOP.bnn_core__DOT__pe_array__BRA__5__KET____DOT__pe__DOT__clk), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_bnn_core__pe_array__BRA__5__KET____pe->varInsert("enable", &(TOP.bnn_core__DOT__pe_array__BRA__5__KET____DOT__pe__DOT__enable), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_bnn_core__pe_array__BRA__5__KET____pe->varInsert("i", &(TOP.bnn_core__DOT__pe_array__BRA__5__KET____DOT__pe__DOT__i), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW|VLVF_SIGNED, 0, 1 ,31,0);
    __Vscopep_bnn_core__pe_array__BRA__5__KET____pe->varInsert("inp", &(TOP.bnn_core__DOT__pe_array__BRA__5__KET____DOT__pe__DOT__inp), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_bnn_core__pe_array__BRA__5__KET____pe->varInsert("neuron_value", &(TOP.bnn_core__DOT__pe_array__BRA__5__KET____DOT__pe__DOT__neuron_value), false, VLVT_UINT16, VLVD_NODIR|VLVF_PUB_RW|VLVF_SIGNED, 0, 1 ,9,0);
    __Vscopep_bnn_core__pe_array__BRA__5__KET____pe->varInsert("rstn", &(TOP.bnn_core__DOT__pe_array__BRA__5__KET____DOT__pe__DOT__rstn), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_bnn_core__pe_array__BRA__5__KET____pe->varInsert("stage1", &(TOP.bnn_core__DOT__pe_array__BRA__5__KET____DOT__pe__DOT__stage1), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 1, 1 ,0,15 ,1,0);
    __Vscopep_bnn_core__pe_array__BRA__5__KET____pe->varInsert("stage2", &(TOP.bnn_core__DOT__pe_array__BRA__5__KET____DOT__pe__DOT__stage2), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 1, 1 ,0,7 ,2,0);
    __Vscopep_bnn_core__pe_array__BRA__5__KET____pe->varInsert("stage3", &(TOP.bnn_core__DOT__pe_array__BRA__5__KET____DOT__pe__DOT__stage3), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 1, 1 ,0,3 ,3,0);
    __Vscopep_bnn_core__pe_array__BRA__5__KET____pe->varInsert("stage4", &(TOP.bnn_core__DOT__pe_array__BRA__5__KET____DOT__pe__DOT__stage4), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 1, 1 ,0,1 ,4,0);
    __Vscopep_bnn_core__pe_array__BRA__5__KET____pe->varInsert("sum_reg", &(TOP.bnn_core__DOT__pe_array__BRA__5__KET____DOT__pe__DOT__sum_reg), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,5,0);
    __Vscopep_bnn_core__pe_array__BRA__5__KET____pe->varInsert("threshold", &(TOP.bnn_core__DOT__pe_array__BRA__5__KET____DOT__pe__DOT__threshold), false, VLVT_UINT16, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,9,0);
    __Vscopep_bnn_core__pe_array__BRA__5__KET____pe->varInsert("weight_buffer", &(TOP.bnn_core__DOT__pe_array__BRA__5__KET____DOT__pe__DOT__weight_buffer), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_bnn_core__pe_array__BRA__5__KET____pe->varInsert("wt", &(TOP.bnn_core__DOT__pe_array__BRA__5__KET____DOT__pe__DOT__wt), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_bnn_core__pe_array__BRA__5__KET____pe->varInsert("xnor_result", &(TOP.bnn_core__DOT__pe_array__BRA__5__KET____DOT__pe__DOT__xnor_result), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_bnn_core__pe_array__BRA__6__KET____pe->varInsert("accumulator", &(TOP.bnn_core__DOT__pe_array__BRA__6__KET____DOT__pe__DOT__accumulator), false, VLVT_UINT16, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,9,0);
    __Vscopep_bnn_core__pe_array__BRA__6__KET____pe->varInsert("activations_buffer", &(TOP.bnn_core__DOT__pe_array__BRA__6__KET____DOT__pe__DOT__activations_buffer), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_bnn_core__pe_array__BRA__6__KET____pe->varInsert("clear_accumulator", &(TOP.bnn_core__DOT__pe_array__BRA__6__KET____DOT__pe__DOT__clear_accumulator), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_bnn_core__pe_array__BRA__6__KET____pe->varInsert("clk", &(TOP.bnn_core__DOT__pe_array__BRA__6__KET____DOT__pe__DOT__clk), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_bnn_core__pe_array__BRA__6__KET____pe->varInsert("enable", &(TOP.bnn_core__DOT__pe_array__BRA__6__KET____DOT__pe__DOT__enable), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_bnn_core__pe_array__BRA__6__KET____pe->varInsert("i", &(TOP.bnn_core__DOT__pe_array__BRA__6__KET____DOT__pe__DOT__i), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW|VLVF_SIGNED, 0, 1 ,31,0);
    __Vscopep_bnn_core__pe_array__BRA__6__KET____pe->varInsert("inp", &(TOP.bnn_core__DOT__pe_array__BRA__6__KET____DOT__pe__DOT__inp), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_bnn_core__pe_array__BRA__6__KET____pe->varInsert("neuron_value", &(TOP.bnn_core__DOT__pe_array__BRA__6__KET____DOT__pe__DOT__neuron_value), false, VLVT_UINT16, VLVD_NODIR|VLVF_PUB_RW|VLVF_SIGNED, 0, 1 ,9,0);
    __Vscopep_bnn_core__pe_array__BRA__6__KET____pe->varInsert("rstn", &(TOP.bnn_core__DOT__pe_array__BRA__6__KET____DOT__pe__DOT__rstn), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_bnn_core__pe_array__BRA__6__KET____pe->varInsert("stage1", &(TOP.bnn_core__DOT__pe_array__BRA__6__KET____DOT__pe__DOT__stage1), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 1, 1 ,0,15 ,1,0);
    __Vscopep_bnn_core__pe_array__BRA__6__KET____pe->varInsert("stage2", &(TOP.bnn_core__DOT__pe_array__BRA__6__KET____DOT__pe__DOT__stage2), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 1, 1 ,0,7 ,2,0);
    __Vscopep_bnn_core__pe_array__BRA__6__KET____pe->varInsert("stage3", &(TOP.bnn_core__DOT__pe_array__BRA__6__KET____DOT__pe__DOT__stage3), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 1, 1 ,0,3 ,3,0);
    __Vscopep_bnn_core__pe_array__BRA__6__KET____pe->varInsert("stage4", &(TOP.bnn_core__DOT__pe_array__BRA__6__KET____DOT__pe__DOT__stage4), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 1, 1 ,0,1 ,4,0);
    __Vscopep_bnn_core__pe_array__BRA__6__KET____pe->varInsert("sum_reg", &(TOP.bnn_core__DOT__pe_array__BRA__6__KET____DOT__pe__DOT__sum_reg), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,5,0);
    __Vscopep_bnn_core__pe_array__BRA__6__KET____pe->varInsert("threshold", &(TOP.bnn_core__DOT__pe_array__BRA__6__KET____DOT__pe__DOT__threshold), false, VLVT_UINT16, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,9,0);
    __Vscopep_bnn_core__pe_array__BRA__6__KET____pe->varInsert("weight_buffer", &(TOP.bnn_core__DOT__pe_array__BRA__6__KET____DOT__pe__DOT__weight_buffer), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_bnn_core__pe_array__BRA__6__KET____pe->varInsert("wt", &(TOP.bnn_core__DOT__pe_array__BRA__6__KET____DOT__pe__DOT__wt), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_bnn_core__pe_array__BRA__6__KET____pe->varInsert("xnor_result", &(TOP.bnn_core__DOT__pe_array__BRA__6__KET____DOT__pe__DOT__xnor_result), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_bnn_core__pe_array__BRA__7__KET____pe->varInsert("accumulator", &(TOP.bnn_core__DOT__pe_array__BRA__7__KET____DOT__pe__DOT__accumulator), false, VLVT_UINT16, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,9,0);
    __Vscopep_bnn_core__pe_array__BRA__7__KET____pe->varInsert("activations_buffer", &(TOP.bnn_core__DOT__pe_array__BRA__7__KET____DOT__pe__DOT__activations_buffer), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_bnn_core__pe_array__BRA__7__KET____pe->varInsert("clear_accumulator", &(TOP.bnn_core__DOT__pe_array__BRA__7__KET____DOT__pe__DOT__clear_accumulator), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_bnn_core__pe_array__BRA__7__KET____pe->varInsert("clk", &(TOP.bnn_core__DOT__pe_array__BRA__7__KET____DOT__pe__DOT__clk), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_bnn_core__pe_array__BRA__7__KET____pe->varInsert("enable", &(TOP.bnn_core__DOT__pe_array__BRA__7__KET____DOT__pe__DOT__enable), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_bnn_core__pe_array__BRA__7__KET____pe->varInsert("i", &(TOP.bnn_core__DOT__pe_array__BRA__7__KET____DOT__pe__DOT__i), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW|VLVF_SIGNED, 0, 1 ,31,0);
    __Vscopep_bnn_core__pe_array__BRA__7__KET____pe->varInsert("inp", &(TOP.bnn_core__DOT__pe_array__BRA__7__KET____DOT__pe__DOT__inp), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_bnn_core__pe_array__BRA__7__KET____pe->varInsert("neuron_value", &(TOP.bnn_core__DOT__pe_array__BRA__7__KET____DOT__pe__DOT__neuron_value), false, VLVT_UINT16, VLVD_NODIR|VLVF_PUB_RW|VLVF_SIGNED, 0, 1 ,9,0);
    __Vscopep_bnn_core__pe_array__BRA__7__KET____pe->varInsert("rstn", &(TOP.bnn_core__DOT__pe_array__BRA__7__KET____DOT__pe__DOT__rstn), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_bnn_core__pe_array__BRA__7__KET____pe->varInsert("stage1", &(TOP.bnn_core__DOT__pe_array__BRA__7__KET____DOT__pe__DOT__stage1), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 1, 1 ,0,15 ,1,0);
    __Vscopep_bnn_core__pe_array__BRA__7__KET____pe->varInsert("stage2", &(TOP.bnn_core__DOT__pe_array__BRA__7__KET____DOT__pe__DOT__stage2), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 1, 1 ,0,7 ,2,0);
    __Vscopep_bnn_core__pe_array__BRA__7__KET____pe->varInsert("stage3", &(TOP.bnn_core__DOT__pe_array__BRA__7__KET____DOT__pe__DOT__stage3), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 1, 1 ,0,3 ,3,0);
    __Vscopep_bnn_core__pe_array__BRA__7__KET____pe->varInsert("stage4", &(TOP.bnn_core__DOT__pe_array__BRA__7__KET____DOT__pe__DOT__stage4), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 1, 1 ,0,1 ,4,0);
    __Vscopep_bnn_core__pe_array__BRA__7__KET____pe->varInsert("sum_reg", &(TOP.bnn_core__DOT__pe_array__BRA__7__KET____DOT__pe__DOT__sum_reg), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,5,0);
    __Vscopep_bnn_core__pe_array__BRA__7__KET____pe->varInsert("threshold", &(TOP.bnn_core__DOT__pe_array__BRA__7__KET____DOT__pe__DOT__threshold), false, VLVT_UINT16, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,9,0);
    __Vscopep_bnn_core__pe_array__BRA__7__KET____pe->varInsert("weight_buffer", &(TOP.bnn_core__DOT__pe_array__BRA__7__KET____DOT__pe__DOT__weight_buffer), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_bnn_core__pe_array__BRA__7__KET____pe->varInsert("wt", &(TOP.bnn_core__DOT__pe_array__BRA__7__KET____DOT__pe__DOT__wt), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_bnn_core__pe_array__BRA__7__KET____pe->varInsert("xnor_result", &(TOP.bnn_core__DOT__pe_array__BRA__7__KET____DOT__pe__DOT__xnor_result), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_bnn_core__unnamedblk1->varInsert("n", &(TOP.bnn_core__DOT__unnamedblk1__DOT__n), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY|VLVF_SIGNED, 0, 1 ,31,0);
    __Vscopep_bnn_core__unnamedblk2->varInsert("n", &(TOP.bnn_core__DOT__unnamedblk2__DOT__n), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY|VLVF_SIGNED, 0, 1 ,31,0);
    __Vscopep_constants_pkg->varInsert("ACCUM_WIDTH", const_cast<void*>(static_cast<const void*>(&(TOP__constants_pkg.ACCUM_WIDTH))), true, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY|VLVF_SIGNED, 0, 1 ,31,0);
    __Vscopep_constants_pkg->varInsert("NUM_PE", const_cast<void*>(static_cast<const void*>(&(TOP__constants_pkg.NUM_PE))), true, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY|VLVF_SIGNED, 0, 1 ,31,0);
    __Vscopep_constants_pkg->varInsert("TOTAL_WORDS", const_cast<void*>(static_cast<const void*>(&(TOP__constants_pkg.TOTAL_WORDS))), true, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY|VLVF_SIGNED, 0, 1 ,31,0);
    __Vscopep_constants_pkg->varInsert("WORD_WIDTH", const_cast<void*>(static_cast<const void*>(&(TOP__constants_pkg.WORD_WIDTH))), true, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY|VLVF_SIGNED, 0, 1 ,31,0);
}

Vtop__Syms::~Vtop__Syms() {
    // Tear down scope hierarchy
    __Vhier.remove(0, __Vscopep_bnn_core);
    __Vhier.remove(0, __Vscopep_constants_pkg);
    __Vhier.remove(__Vscopep_bnn_core, __Vscopep_bnn_core__pe_array__BRA__0__KET__);
    __Vhier.remove(__Vscopep_bnn_core, __Vscopep_bnn_core__pe_array__BRA__1__KET__);
    __Vhier.remove(__Vscopep_bnn_core, __Vscopep_bnn_core__pe_array__BRA__2__KET__);
    __Vhier.remove(__Vscopep_bnn_core, __Vscopep_bnn_core__pe_array__BRA__3__KET__);
    __Vhier.remove(__Vscopep_bnn_core, __Vscopep_bnn_core__pe_array__BRA__4__KET__);
    __Vhier.remove(__Vscopep_bnn_core, __Vscopep_bnn_core__pe_array__BRA__5__KET__);
    __Vhier.remove(__Vscopep_bnn_core, __Vscopep_bnn_core__pe_array__BRA__6__KET__);
    __Vhier.remove(__Vscopep_bnn_core, __Vscopep_bnn_core__pe_array__BRA__7__KET__);
    __Vhier.remove(__Vscopep_bnn_core, __Vscopep_bnn_core__unnamedblk1);
    __Vhier.remove(__Vscopep_bnn_core, __Vscopep_bnn_core__unnamedblk2);
    __Vhier.remove(__Vscopep_bnn_core__pe_array__BRA__0__KET__, __Vscopep_bnn_core__pe_array__BRA__0__KET____pe);
    __Vhier.remove(__Vscopep_bnn_core__pe_array__BRA__1__KET__, __Vscopep_bnn_core__pe_array__BRA__1__KET____pe);
    __Vhier.remove(__Vscopep_bnn_core__pe_array__BRA__2__KET__, __Vscopep_bnn_core__pe_array__BRA__2__KET____pe);
    __Vhier.remove(__Vscopep_bnn_core__pe_array__BRA__3__KET__, __Vscopep_bnn_core__pe_array__BRA__3__KET____pe);
    __Vhier.remove(__Vscopep_bnn_core__pe_array__BRA__4__KET__, __Vscopep_bnn_core__pe_array__BRA__4__KET____pe);
    __Vhier.remove(__Vscopep_bnn_core__pe_array__BRA__5__KET__, __Vscopep_bnn_core__pe_array__BRA__5__KET____pe);
    __Vhier.remove(__Vscopep_bnn_core__pe_array__BRA__6__KET__, __Vscopep_bnn_core__pe_array__BRA__6__KET____pe);
    __Vhier.remove(__Vscopep_bnn_core__pe_array__BRA__7__KET__, __Vscopep_bnn_core__pe_array__BRA__7__KET____pe);
    // Clear keys from hierarchy map after values have been removed
    __Vhier.clear();
    // Tear down scopes
    VL_DO_CLEAR(delete __Vscopep_TOP, __Vscopep_TOP = nullptr);
    VL_DO_CLEAR(delete __Vscopep_bnn_core, __Vscopep_bnn_core = nullptr);
    VL_DO_CLEAR(delete __Vscopep_bnn_core__pe_array__BRA__0__KET__, __Vscopep_bnn_core__pe_array__BRA__0__KET__ = nullptr);
    VL_DO_CLEAR(delete __Vscopep_bnn_core__pe_array__BRA__0__KET____pe, __Vscopep_bnn_core__pe_array__BRA__0__KET____pe = nullptr);
    VL_DO_CLEAR(delete __Vscopep_bnn_core__pe_array__BRA__1__KET__, __Vscopep_bnn_core__pe_array__BRA__1__KET__ = nullptr);
    VL_DO_CLEAR(delete __Vscopep_bnn_core__pe_array__BRA__1__KET____pe, __Vscopep_bnn_core__pe_array__BRA__1__KET____pe = nullptr);
    VL_DO_CLEAR(delete __Vscopep_bnn_core__pe_array__BRA__2__KET__, __Vscopep_bnn_core__pe_array__BRA__2__KET__ = nullptr);
    VL_DO_CLEAR(delete __Vscopep_bnn_core__pe_array__BRA__2__KET____pe, __Vscopep_bnn_core__pe_array__BRA__2__KET____pe = nullptr);
    VL_DO_CLEAR(delete __Vscopep_bnn_core__pe_array__BRA__3__KET__, __Vscopep_bnn_core__pe_array__BRA__3__KET__ = nullptr);
    VL_DO_CLEAR(delete __Vscopep_bnn_core__pe_array__BRA__3__KET____pe, __Vscopep_bnn_core__pe_array__BRA__3__KET____pe = nullptr);
    VL_DO_CLEAR(delete __Vscopep_bnn_core__pe_array__BRA__4__KET__, __Vscopep_bnn_core__pe_array__BRA__4__KET__ = nullptr);
    VL_DO_CLEAR(delete __Vscopep_bnn_core__pe_array__BRA__4__KET____pe, __Vscopep_bnn_core__pe_array__BRA__4__KET____pe = nullptr);
    VL_DO_CLEAR(delete __Vscopep_bnn_core__pe_array__BRA__5__KET__, __Vscopep_bnn_core__pe_array__BRA__5__KET__ = nullptr);
    VL_DO_CLEAR(delete __Vscopep_bnn_core__pe_array__BRA__5__KET____pe, __Vscopep_bnn_core__pe_array__BRA__5__KET____pe = nullptr);
    VL_DO_CLEAR(delete __Vscopep_bnn_core__pe_array__BRA__6__KET__, __Vscopep_bnn_core__pe_array__BRA__6__KET__ = nullptr);
    VL_DO_CLEAR(delete __Vscopep_bnn_core__pe_array__BRA__6__KET____pe, __Vscopep_bnn_core__pe_array__BRA__6__KET____pe = nullptr);
    VL_DO_CLEAR(delete __Vscopep_bnn_core__pe_array__BRA__7__KET__, __Vscopep_bnn_core__pe_array__BRA__7__KET__ = nullptr);
    VL_DO_CLEAR(delete __Vscopep_bnn_core__pe_array__BRA__7__KET____pe, __Vscopep_bnn_core__pe_array__BRA__7__KET____pe = nullptr);
    VL_DO_CLEAR(delete __Vscopep_bnn_core__unnamedblk1, __Vscopep_bnn_core__unnamedblk1 = nullptr);
    VL_DO_CLEAR(delete __Vscopep_bnn_core__unnamedblk2, __Vscopep_bnn_core__unnamedblk2 = nullptr);
    VL_DO_CLEAR(delete __Vscopep_constants_pkg, __Vscopep_constants_pkg = nullptr);
    // Tear down sub module instances
    TOP__constants_pkg.dtor();
}
